---
title: "Example Output"
format: html
---

```{r}
library(ggplot2)
```

## Plot 1


```{r}
# Add a label column for legend
red_bars <- data.frame(
  xmin = c(0, 2),
  xmax = c(1, 3),
  ymin = 0,
  ymax = 2,
  type = "Prediction"
)

blue_bars <- data.frame(
  xmin = c(0.5, 6.1),
  xmax = c(3.1, 7.6),
  ymin = 0.4,
  ymax = 0.9,
  type = "Humpback"
)

vlines <- data.frame(x = seq(0, 10, by = 1))
```

```{r}
ggplot() +
  # Vertical lines
  geom_vline(
    data = vlines,
    aes(xintercept = x),
    color = "black",
    linewidth = 0.3
  ) +
  
  # Rectangles with mapped fill
  geom_rect(
    data = red_bars,
    aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = type),
    alpha = 0.9
  ) +
  
  geom_rect(
    data = blue_bars,
    aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = type),
    alpha = 0.9
  ) +
  
  # Manual legend
  scale_fill_manual(
    name = "Signal Type",
    values = c("Prediction" = "#d97a73",
               "Humpback" = "#4f83b6")
  ) +
  
  labs(x = "Time (seconds)", y = "Frequency (Hz)") +
  scale_x_continuous(
  breaks = seq(0, 10, by = 0.5),
  limits = c(0, 10),
  expand = c(0, 0)
) + scale_y_continuous(
  breaks = seq(0, 2, by = 0.1),
  limits = c(0, 2),
  expand = c(0, 0)
) + 
theme(
  panel.grid = element_blank(),
  panel.background = element_rect(fill = "white", color = NA),
  plot.background = element_rect(fill = "white", color = NA),
  axis.line = element_line(color = "black"),
  legend.position = "inside",
  legend.position.inside = c(0.5, 0.98),
  legend.justification = c("center", "top"),
  legend.background = element_rect(fill = "white", color = "black"),
  axis.title.y = element_text(angle = 0, vjust = 0.5)
)  + ggtitle("Example of Poor Per-Vocalization Predictions")

```

```{r}
library(ggplot2)
```

## Plot 2


```{r}
# Add a label column for legend
red_bars <- data.frame(
  xmin = c(6, 2),
  xmax = c(7, 3),
  ymin = 0,
  ymax = 2,
  type = "Prediction"
)

blue_bars <- data.frame(
  xmin = c(0.5, 6.1),
  xmax = c(3.1, 7.6),
  ymin = 0.4,
  ymax = 0.9,
  type = "Humpback"
)

vlines <- data.frame(x = seq(0, 10, by = 1))
```

```{r}
ggplot() +
  # Vertical lines
  geom_vline(
    data = vlines,
    aes(xintercept = x),
    color = "black",
    linewidth = 0.3
  ) +
  
  # Rectangles with mapped fill
  geom_rect(
    data = red_bars,
    aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = type),
    alpha = 0.9
  ) +
  
  geom_rect(
    data = blue_bars,
    aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = type),
    alpha = 0.9
  ) +
  
  # Manual legend
  scale_fill_manual(
    name = "Signal Type",
    values = c("Prediction" = "#d97a73",
               "Humpback" = "#4f83b6")
  ) +
  
  labs(x = "Time (seconds)", y = "Frequency (Hz)") +
  scale_x_continuous(
  breaks = seq(0, 10, by = 0.5),
  limits = c(0, 10),
  expand = c(0, 0)
) + scale_y_continuous(
  breaks = seq(0, 2, by = 0.1),
  limits = c(0, 2),
  expand = c(0, 0)
) + 
theme(
  panel.grid = element_blank(),
  panel.background = element_rect(fill = "white", color = NA),
  plot.background = element_rect(fill = "white", color = NA),
  axis.line = element_line(color = "black"),
  legend.position = "inside",
  legend.position.inside = c(0.5, 0.98),
  legend.justification = c("center", "top"),
  legend.background = element_rect(fill = "white", color = "black"),
  axis.title.y = element_text(angle = 0, vjust = 0.5)
)  + ggtitle("Example of Good Per-Vocalization Predictions")

```



