---
title: "New Audio Conversion Mel"
format: html
editor: source
---



```{r}
library(tuneR)
library(seewave)
library(tidyr)
library(dplyr)
library(readxl)
```

```{r}
source("AudioConversionFunction.R")

```

```{r}
mel_observation_dataframe = function(wav_file_path, 
                                     annotation_file_path,
                                     output_file_name,
                                     start_time = 0,
                                     end_time = 1,
                                     step_time = 0.1,
                                     overlap_time = 0.05,
                                     num_ceps = 12,
                                     max_freq = 2000
                                     ){

  timesteps = melcoeffs(wave_file = wav_file_path,
            start_time = start_time,
            end_time = end_time,
            step_time = step_time,
            overlap_time = overlap_time,
            num_ceps = num_ceps,
            max_freq = max_freq)
  
  
  ranges = import_annotations(annotation_file_path)
  
  
  overlapstart = lapply(timesteps$Time_Start, check_in_ranges, ranges = ranges, 
                        timesteplength = step_time)
  
  annotatedfull = creating_observation_dataframe(overlaps = overlapstart,
                                                 timesteps = timesteps)
  
  
  annotatedfull = add_instances(annotatedfull)
  
  write.csv(annotatedfull, here::here(output_file_name))
  
  return(annotatedfull)
  

}

# function with: 
# wave file path, 
# annotation file path
# start time (minutes)
# end time (minutes)
# step time (seconds)
# overlap time (seconds) 
# number of mel coefficients (default 12)

test = mel_observation_dataframe(
  wav_file_path = here::here("TrainingData", "AW", "671658014.180928183606-AW.wav"),
            annotation_file_path = here::here("TrainingData", "AW", "AWhb.xlsx"),
            output_file_name = "annotatedMelAWFull2000-1.csv",
            start_time = 0,
            end_time = 60,
            step_time = 0.1,
            overlap_time = 0.05,
            num_ceps = 12,
            max_freq = 2000)

# set overlap_time = step_time if no overlap is desired

# sound wave file is ~ 10797.839 seconds long (179.964)
```