---
title: "Random Forest Validation"
format: html
---


## Loading Libraries

```{r}
library(tuneR)
library(seewave)
library(tidyr)
library(dplyr)
library(readxl)
library(ggplot2)
library(ranger)
library(tidyverse)
library(tidymodels)
library(kknn)
library(discrim)
library(purrr)
library(yardstick)
```


## Sourcing

```{r}
source(here::here("ContextWindows", "ContextWindowFunction.R"))
source(here::here("EvaluationWindows", "RollingAverage.R"))
source(here::here("TestingPredictionIntervals.R"))
```


## Loading In Data

```{r}
data_train = read.csv(here::here("TrainingSet", "AWnooverlap.csv")) %>%
  mutate(Humpback = as.factor(Humpback))


data_test = read.csv(here::here("EvaluationSet", "annotatedMELAWFull2000-Testing.csv")) %>% 
  mutate(Humpback = as.factor(Humpback)) %>% filter(X %% 2 == 1)
#annotatedMelAW %>% arrange(desc(Time_End))
```




## Creating Training Data

```{r}

trainingdata = add_observations_linear_tolerance(whaledf = data_train,
                                start_time = 0,
                                end_time =  7199.9,
                                num_time_steps = 20, 
                                numcep = 12,
                                step_size = 0.1,
                                jump_size = 1)



table(trainingdata$Humpback)

trainingdata %>% select(Time_Start, Time_End, Humpback)

```

## Creating Testing Data


```{r}
testingdata = add_observations_linear_tolerance(whaledf = data_test,
                                start_time = 7200,
                                end_time =  max(data_test$Time_Start),
                                num_time_steps = 20, 
                                numcep = 12,
                                step_size = 0.1,
                                jump_size = 1)

testingdata %>% select(Time_Start, Time_End, Humpback)

table(testingdata$Humpback)
```




## Loading in Annotations

```{r}
manual_annotations_evaluation = 
  read_excel(here::here("OrigData", "AW", "AWhb.xlsx")) %>% 
    rename(Begin_Time = 'Begin Time (s)', End_Time = 'End Time (s)') %>%
  filter(Begin_Time >= min(testingdata$Time_Start) & End_Time <= max(testingdata$Time_End))

nrow(manual_annotations_evaluation)
```




## Creating Final Model

```{r}

#creating model
rfmod_1 <- rand_forest(min_n = 1, trees = 1500,
                       mtry = floor(sqrt(ncol(trainingdata) - 3))) %>%
  set_engine("ranger") %>%               
  set_mode("classification")            

#creating recipe
rfrecipe_1 <- recipe(Humpback ~ ., data = trainingdata) %>%
  step_rm(Time_Start, Time_End) %>%
  step_normalize(all_numeric_predictors()) %>%
  step_dummy(all_factor_predictors())


#creating workflow
rfworkflow_1 <- workflow() %>%
  add_model(rfmod_1) %>%
  add_recipe(rfrecipe_1)



#fitting model
rffit_1 <- rfworkflow_1 %>% fit(data = trainingdata)


```




## Predicting on Testing Data

```{r}

predictionsdf <- testingdata %>%
  bind_cols(
    predict(rffit_1, testingdata, type = "class"),
    predict(rffit_1, testingdata, type = "prob")
  ) %>% rename(preds = .pred_class)

table(predictionsdf$preds)


# 
# predictionsdf %>% select(Time_Start, Time_End, Humpback, .pred_class)
# 
# table(predictionsdf$.pred_class)
# 
# 
# 


predictionsdf %>%
  conf_mat(truth = Humpback, estimate = preds)

# type 1 metrics

data.frame(trees = 1500,
           min_n = 1,
           recall = recall(predictionsdf, truth = Humpback, estimate = preds, event_level = "second")$.estimate,
           precision = precision(predictionsdf, truth = Humpback, estimate = preds, event_level = "second")$.estimate, 
           F1 = f_meas(predictionsdf, truth = Humpback, estimate = preds, beta = 1, event_level = "second")$.estimate, 
           F2 = f_meas(predictionsdf, truth = Humpback, estimate = preds, beta = 2, event_level = "second")$.estimate
)

```

## Rolling Average Calculation


```{r}
rolling_avg_centered_base <- function(df, value_col = ".pred_class", n = 5) {
  
  
  x <- df[[value_col]]
  N <- length(x)
  
  rolling_avg <- rep(NA, N)
  
  for (i in seq_len(N)) {
    start <- i - n
    end <- i + n
    
    # only compute if full window is available
    if (start >= 1 && end <= N) {
      rolling_avg[i] <- mean(x[start:end])
    }
  }
  
  df$rolling_avg <- rolling_avg
  return(df)
}

rolling_avg_centered_base(df = predictionsdf, value_col = ".pred_class", n = 1)

```




## Testing Different Thresholds


```{r}
compute_metrics_by_threshold <- function(df, truth_col = "Humpback", prob_col = ".pred_1") {
  thresholds <- seq(0, 1, by = 0.01)
  
  results <- data.frame(
    threshold = numeric(),
    precision = numeric(),
    recall = numeric(),
    f1 = numeric(),
    f2 = numeric()
  )
  
  for (t in thresholds) {
    pred <- ifelse(df[[prob_col]] >= t, 1, 0)
    truth <- df[[truth_col]]
    
    TP <- sum(pred == 1 & truth == 1)
    FP <- sum(pred == 1 & truth == 0)
    FN <- sum(pred == 0 & truth == 1)
    
    precision <- ifelse((TP + FP) == 0, NA, TP / (TP + FP))
    recall <- ifelse((TP + FN) == 0, NA, TP / (TP + FN))
    
    f1 <- ifelse(is.na(precision) | is.na(recall) | (precision + recall) == 0,
                 NA,
                 2 * (precision * recall) / (precision + recall))
    
    f2 <- ifelse(is.na(precision) | is.na(recall) | (4 * precision + recall) == 0,
                 NA,
                 5 * (precision * recall) / (4 * precision + recall))
    
    results <- rbind(results, data.frame(
      threshold = t,
      recall = recall,
      precision = precision,
      f1 = f1,
      f2 = f2
    ))
  }
  
  return(results)
}



df <- data.frame(
  truth = c(0, 1, 0, 1),
  probability = c(0.15, 0.85, 0.4, 0.65)
)

metrics <- compute_metrics_by_threshold(predictionsdf)
print(metrics)

```



## Creating Aggregation Grid

```{r}
# agg_window_length = c(1, 2, 4, 6, 8)
# agg_window_threshold = seq(0, 0.5, by = 0.05)

 
agg_window_length = c(0.001)
agg_window_threshold = c(0.5)

```


```{r}



grid <- expand.grid(
  lengths = agg_window_length,
  thresholds = agg_window_threshold
)

grid

```



## Metrics Type 1

```{r}

predictionsdf %>%
  conf_mat(truth = Humpback, estimate = preds)
```

```{r}
whale_call_metrics_type1 <- function(row, predictionsdf) {
  # agg_window_length <- as.numeric(row[1])
  # agg_window_threshold <- as.numeric(row[2])

  rolling_average <- rolling_avg_df(
    predictionsdf,
    agg_window_length,
    agg_window_threshold
  )
  
  #print(rolling_average)
    
  if (nrow(rolling_average %>% filter(rolling_avg_prediction == 1)) == 0) {
    rfeval_recall <- 0
    rfeval_precision <- NA
    
  } else if (nrow(rolling_average %>% filter(rolling_avg_prediction == 0)) == 0) {
    rfeval_recall <- 1
    rfeval_precision <- nrow(rolling_average %>% filter(Humpback == 1)) /
      nrow(rolling_average %>% filter(rolling_avg_prediction == 1))
    
  } else if (nrow(rolling_average %>% filter(Humpback == 1)) == 0) {
    rfeval_recall <- NA
    rfeval_precision <- 0
    
  } else {
    rfeval_recall <- rolling_average %>%
      recall(truth = Humpback, estimate = rolling_avg_prediction, event_level = "second") %>%
      pull(.estimate)
    
    rfeval_precision <- rolling_average %>%
      precision(truth = Humpback, estimate = rolling_avg_prediction, event_level = "second") %>%
      pull(.estimate)
  }
  
  rfeval_f1 <- (2 * rfeval_recall * rfeval_precision) / (rfeval_recall + rfeval_precision)
  rfeval_f2 <- (5 * rfeval_recall * rfeval_precision) / (rfeval_recall + 4 * rfeval_precision)
  
  data.frame(
    agg_window_length = agg_window_length,
    agg_window_threshold = agg_window_threshold,
    Recall = rfeval_recall,
    Precision = rfeval_precision,
    F1 = rfeval_f1,
    F2 = rfeval_f2
  )
}


predictionsdf = predictionsdf %>% rename(preds = .pred_class)

final_df <- do.call(
  rbind,
  lapply(seq_len(nrow(grid)), function(i) {
    whale_call_metrics_type1(grid[i, ], predictionsdf)
  })
)

final_df %>% arrange(desc(F2))
```



## Metrics Type 2


```{r}
whale_call_metrics_type2 <- function(predictionsdf) {
  # agg_window_length <- as.numeric(row[1])
  # agg_window_threshold <- as.numeric(row[2])

  # rolling_average <- rolling_avg_df(
  #   predictionsdf,
  #   agg_window_length,
  #   agg_window_threshold
  # )
  # 
  # print(rolling_average)

  # prediction_windows <- creating_prediction_windows(
  #   rolling_average,
  #   time_start = Time_Start,
  #   time_end = Time_End,
  #   value_col = rolling_avg_prediction
  # )
  
  
  positive_windows = predictionsdf %>% filter(preds == 1)
  
  print(positive_windows)

  # conf_matrix_table <- confusion_from_intervals(
  #   data_true = manual_annotations_evaluation,
  #   data_pred = prediction_windows,
  #   true_interval_start = Begin_Time,
  #   true_interval_end = End_Time,
  #   pred_interval_start = start_time,
  #   pred_interval_end = end_time
  # )
  # 
  
  conf_matrix_table <- confusion_from_intervals(
    data_true = manual_annotations_evaluation,
    data_pred = positive_windows,
    true_interval_start = Begin_Time,
    true_interval_end = End_Time,
    pred_interval_start = Time_Start,
    pred_interval_end = Time_End
  )
  
  
  

  TP <- conf_matrix_table %>% dplyr::pull(TP)
  FN <- conf_matrix_table %>% dplyr::pull(FN)
  FP <- conf_matrix_table %>% dplyr::pull(FP)

  print(TP)
  print(FN)
  print(FP)
  
  num_pred_windows <- nrow(positive_windows)
  num_calls_detected = TP

  if (TP + FN == 0) {
    recall <- NA_real_
  } else {
    recall <- TP / (TP + FN)
  }

  if (TP + FP == 0) {
    precision <- NA_real_
  } else {
    precision <- TP / (TP + FP)
  }

  if (is.na(recall) || is.na(precision) || (recall + precision == 0)) {
    F1 <- NA_real_
  } else {
    F1 <- 2 * recall * precision / (recall + precision)
  }

  if (is.na(recall) || is.na(precision) || (4 * precision + recall == 0)) {
    F2 <- NA_real_
  } else {
    F2 <- 5 * precision * recall / (4 * precision + recall)
  }

  data.frame(
    TP = TP,
    FN = FN,
    FP = FP,
    num_pred_windows = num_pred_windows,
    recall = recall,
    precision = precision,
    F1 = F1,
    F2 = F2
  )
}


whale_call_metrics_type2(predictionsdf)

manual_annotations_evaluation
```




## Saving Predictions of Best Parameters


```{r}
prediction_windows_best <- creating_prediction_windows(
  predictionsdf,
  time_start = Time_Start,
  time_end = Time_End,
  value_col = preds
)

predictionsdf %>% select(Time_Start, Time_End, Humpback, preds) %>% filter(preds == 1)

prediction_windows_best
```





## Create Output For Raven Visualization

```{r}

raven_output = function(windows){
  print(windows)
  #creating dummy low and high frequencies
  windows = windows %>% 
    rename("Begin Time (s)" = start_time, "End Time (s)" = end_time) %>% 
    mutate("Low Freq (Hz)" = 0, "High Freq (Hz)" = 1400) %>% 
    dplyr::select(c("Begin Time (s)", "End Time (s)", 
                    "Low Freq (Hz)", "High Freq (Hz)"))
  
  
  #create output 
  write.table(windows, 
              paste0("humpbackmethodrfevalindividualpreds",
                     1, "minn",
                     1500, "trees",
                     "1.6seconds",
                     ".txt"), 
              sep = "\t", row.names = FALSE, quote = FALSE)
}

raven_output(windows = prediction_windows_best)

```