---
title: "DumbQDAModel"
format: html
editor: visual
---

```{r}
#| label: libraries-r


library(tidyverse)
library(tidymodels)
library(kknn)
library(tidyr)
library(dplyr)
library(readxl)
library(discrim)
library(klaR)
```

## Loading and Transforming Data

```{r}
training = read_csv("C:/Users/lucas/Desktop/Thesis/Code/annotatedmelAW.csv") #AW annotated data

training = training %>% mutate(Humpback = as.factor(Humpback))

testing1 = read_csv("C:/Users/lucas/Desktop/Thesis/Code/annotatedmelAS.csv")

testing1 = testing1 %>% mutate(Humpback = as.factor(Humpback))


testing2 = read_csv("C:/Users/lucas/Desktop/Thesis/Code/annotatedmelSS.csv")

testing2 = testing2 %>% mutate(Humpback = as.factor(Humpback))


```

## Creating Cross-Validation Folds

```{r}
set.seed(8656)
training_cvs = vfold_cv(training, v = 10)

```

## Creating Model

```{r}
#creating QDA model
qda_mod1 = discrim_regularized(frac_common_cov = 0) %>%
  set_engine("klaR") %>% set_mode("classification")


#creating recipe
qdarecipe_1 = recipe(Humpback ~ V1 + V2 + V3 + V4 + V5 + 
                       V6 + V7 + V8 + V9 + V10, 
                     data = training) %>%
  step_normalize(all_numeric_predictors()) %>%
  step_dummy(all_factor_predictors())


#creating workflow
qdaworkflow_1 = workflow() %>% 
  add_recipe(qdarecipe_1) %>% 
  add_model(qda_mod1)

#fitting model
qdafit_1 = qdaworkflow_1 %>% fit(training) 


#confusion matrix
training %>%
  mutate(
    qdapreds = predict(qdafit_1, training)$.pred_class
  ) %>%
  conf_mat(truth = Humpback,
           estimate = qdapreds)
```

## Cross Validating

```{r}
#fitting CVs
qdafitcv_1 = qdaworkflow_1 %>% fit_resamples(training_cvs,
                metrics = metric_set(accuracy, roc_auc, precision, specificity, recall)
                )

#results
collect_metrics(qdafitcv_1)
#0.652
```

## Validating on Other Models

```{r}

#as.data.frame(predict(qdafit_1, testing1)$.pred_class, testing1$Humpback)


testing1 = testing1 %>%
  mutate(
    qdapreds = predict(qdafit_1, testing1)$.pred_class
  )

testing1 %>%
  conf_mat(truth = Humpback,
           estimate = qdapreds)

recall(testing1, Humpback, qdapreds)

#0.722


#recall is minimizing false negatives, (FN = predicting no HB when it is a HB)




#as.data.frame(predict(qdafit_1, testing2)$.pred_class, testing1$Humpback)


testing2 = testing2 %>%
  mutate(
    qdapreds = predict(qdafit_1, testing2)$.pred_class
  )

testing2 %>%
  conf_mat(truth = Humpback,
           estimate = qdapreds)

recall(testing2, Humpback, qdapreds)

#0.220




```
