---
title: "Annotation Exploratory Data Analysis"
format: html
editor: source
---


## Loading in Libraries

```{r}
library(tidyverse)
library(ggplot2)
library(readxl)
```


## Reading in Annotation Data


```{r}
manualannotations = read_excel(here::here("OrigData", "AW", "AWhb.xlsx"))

colnames(manualannotations)
```

## Mutating Data Set


```{r}

manualannotations = manualannotations %>% rename(begin_time = "Begin Time (s)",
                                                 end_time = "End Time (s)",
                                                 low_freq = "Low Freq (Hz)",
                                                 high_freq = "High Freq (Hz)")



manualannotations = manualannotations %>%
  mutate(diff = lead(begin_time) - end_time)


```


## Duration Summary



```{r}

manualannotations %>%
  ggplot(aes(x = callduration)) + 
  ggtitle("Humpback Whale Call Durations") + 
  labs(x = "Duration (seconds)", y = "Count") +
  geom_histogram(binwidth = 0.25, fill = "blue", color = "black") +
  scale_x_continuous(breaks = 0:10) +
  theme_bw() + 
  theme(panel.grid.minor = element_blank(),
        plot.title = element_text(hjust = 0.5),
        axis.ticks = element_line(color = "black"))
```


## Between_Whale Call Length Summary


```{r}
manualannotations %>% ggplot(aes(x = diff)) + geom_histogram(bins = 31) +
  ggtitle("Histogram of Whale Call Durations")


abc = manualannotations %>% pull(diff)

sort(abc, decreasing = T)



manualannotations %>% filter(diff <= 30) %>% 
  ggplot(aes(x = diff)) + 
  ggtitle("Duration Between Humpback Whale Calls") + 
  labs(x = "Duration (seconds)", y = "Count") +
  geom_histogram(binwidth = 1, fill = "blue", color = "black") +
  scale_x_continuous(breaks = seq(-4, 30, by = 2)) +
  theme_bw() + 
  theme(panel.grid.minor = element_blank(),
        plot.title = element_text(hjust = 0.5),
        axis.ticks = element_line(color = "black"))
```



## Frequency Summary

```{r}
manualannotations %>% 
  ggplot(aes(x = high_freq)) + 
  ggtitle("Highest Frequency of Humpback Whale Calls") + 
  labs(x = "Frequency (Hz)", y = "Count") +
  geom_histogram(binwidth = 20, fill = "blue", color = "black") +
  scale_x_continuous(breaks = seq(0, 2000, by = 100)) +
  theme_bw() + 
  theme(panel.grid.minor = element_blank(),
        plot.title = element_text(hjust = 0.5),
        axis.ticks = element_line(color = "black"))
```


```{r}

summary(manualannotations$callduration) 

manualannotations %>% ggplot(aes(x = high_freq - low_freq)) + geom_histogram(bins = 21)

manualannotations %>% ggplot(aes(x = high_freq)) + geom_histogram(bins = 21)

manualannotations %>% ggplot(aes(x = low_freq)) + geom_histogram(bins = 21)

```


## Overlaps



```{r}
table(manualannotations$overlap)

```


### Start-Start Difference


```{r}
manualannotations %>% ggplot(aes(x = start_start_diff)) + geom_histogram(bins = 21)

```



