---
title: "AudioConversionFFC"
format: html
editor: visual
---

```{r}
library(tuneR)
library(seewave)
library(tidyr)
library(dplyr)
library(readxl)
```

## FFT Binning Example (AI Code)

```{r}


# Example time series data
sampling_rate <- 100 # Hz
time <- seq(0, 2, by = 1/sampling_rate) # 2 seconds of data
signal <- sin(2 * pi * 19 * time) + 0.5 * sin(2 * pi * 45 * time) # Two sine waves

class(signal)

# Perform FFT
fft_result <- fft(signal)


N <- length(signal)


frequencies <- (0:(N-1)) * (sampling_rate / N)

amplitude <- Mod(fft_result)

# Consider only the positive frequencies (first half)
positive_frequencies <- frequencies[1:(N/2 + 1)]
positive_amplitude <- amplitude[1:(N/2 + 1)]


```

```{r}

# Define custom frequency bins
bin_edges <- c(0, 10, 20, 30, 40, sampling_rate/2)
frequency_bins <- cut(positive_frequencies, breaks = bin_edges)

# Aggregate amplitude within each bin (e.g., by summing)
binned_amplitude <- tapply(positive_amplitude, frequency_bins, sum)

# You can also calculate other statistics like mean, max, etc.
# binned_mean_amplitude <- tapply(positive_amplitude, frequency_bins, mean)
```

```{r}
library(seewave)
library(e1071)

# Example: Generate a simple signal with changing frequency
f_samp <- 100 # Sampling frequency

t <- seq(0, 5, by = 1/f_samp) # Time vector

signal <- sin(2 * pi * 5 * t[1:251]) + sin(2 * pi * 20 * t[252:501])
#signal has 251 elemetnts


# Compute STFT, win and inc arguments simlar to MEL
stft_result <- stft(signal, win = 5, inc = 5)

stft_result
```


STFT Applies FFT to Multiple Smaller Windows in Time (e1071 package)


```{r}

```

