---
title: "FFC2"
format: html
editor: visual
---

```{r}
#| label: loading-libraries
#| warning: false

library(tuneR)
library(seewave)
library(tidyr)
library(dplyr)
library(readxl)
```

## Reading in files

```{r}
audio_dataAW <- readWave("C:/Users/lucas/Desktop/Thesis/Code/TrainingData/671658014.180928183606-AW.wav", from = 0, to = 1, units = "seconds")

```

## Extracting Raw Audio Samples

```{r}
raw_samplesAW <- audio_dataAW@left #mono data has identical left and right values
```

## Compute Fourier Transform

```{r}
# Compute the FFT
fft_result <- fft(raw_samplesAW)
#96000 entries
```

```{r}
# Get the amplitude spectrum (taking modularity)
amplitude_spectrum <- Mod(fft_result)

amplitude_spectrum[2]

amplitude_spectrum[47998]

amplitude_spectrum[47999]

amplitude_spectrum[48000]
amplitude_spectrum[48001] #symmetric around entry 48001

amplitude_spectrum[48002]
amplitude_spectrum[48003]
amplitude_spectrum[48004]

amplitude_spectrum[96000]



# Get the sampling rate (# samples per second)
sampling_rate <- audio_dataAW@samp.rate #96000 for whale data

# Create a frequency vector for plotting (only the first half is unique)
n <- length(raw_samplesAW)




frequencies <- seq(from = 0, to = sampling_rate / 2, length.out = n / 2 + 1)



# Consider only the positive frequencies (first half)
positive_frequencies <- frequencies[1:(n/2 + 1)]
positive_amplitude <- amplitude_spectrum[1:(n/2 + 1)]



# Plot the amplitude spectrum (only the first half)
#plot(frequencies, amplitude_spectrum[1:(n/2 + 1)], type = "h",
#     xlab = "Frequency (Hz)", ylab = "Amplitude",
#     main = "Amplitude Spectrum of Audio File")
```

## Creating Bins

```{r}
bin_edges = seq(from = 0, to = 48001, by = 10)

frequency_bins <- cut(positive_frequencies, breaks = bin_edges)

binned_amplitude <- tapply(positive_amplitude, frequency_bins, sum)

binned_amplitude[4800]

sort(binned_amplitude, decreasing = TRUE)
```
