---
title: "Gray Whale Tuning (Random Forest)"
format: html
editor: source
---


## Loading Libraries

```{r}
library(tuneR)
library(seewave)
library(tidyr)
library(dplyr)
library(readxl)
library(ggplot2)
library(ranger)
library(tidyverse)
library(tidymodels)
library(discrim)
library(vctrs)
```

## Sourcing

```{r}
source(here::here("ContextWindows", "ContextWindowFunctions.R"))
source(here::here("EvaluationWindows", "EvaluationWindowFunctions.R"))
source(here::here("CustomDenominator.R"))
```


## Setting Seed for Consistent Randomization

```{r}
set.seed(897)
```


## Loading In Data

```{r}
data = read.csv(here::here("GrayWhaleMethod", "TrainingSet", "GrayWhaleTrainingData.csv")) %>%
  mutate(Humpback = as.factor(Humpback))

tempdata = data %>% filter(Time_Start < 20)


#annotatedMelAW %>% arrange(desc(Time_End))
```


## Creating Training Data

```{r}
trainingdata = add_observations(whaledf = tempdata,
                                start_time = 0,
                                end_time = 20,
                                num_time_steps = 1, 
                                numcep = 13,
                                step_size = 0.1)

trainingdata


manual_annotations = read_excel(here::here("OrigData", "AW", "AWhb.xlsx"))
```




## Balancing (if requested)

```{r}

# need to cross validate instead of train-test
# dont need to use apply function
# just provide list of mtrys and min_n's

# each model needs only a new mtry and min_n, the rest of the tuned metrics are applied after
# predictions are made

balancing = function(trainingdata, balanced = FALSE){

  if (balanced == TRUE){

    numnegatives = nrow(trainingdata %>% filter(Humpback == 0))
  
    # taking row numbers of positive observations
  
    trainingpositives = trainingdata %>% filter(Humpback == 1)
  
    #trainingpositives[sample(c(1:nrow(trainingpositives)), size = numnegatives),]
  
  
    trainingdata = rbind(trainingdata %>% 
                           filter(Humpback == 0), 
                         trainingpositives[sample(c(1:nrow(trainingpositives)), 
                                                  size = numnegatives),])
  }
  return(trainingdata)
  
}

balancing(trainingdata, balanced = FALSE)

balancing(trainingdata, balanced = TRUE)


```

## Tuning Function


```{r}

rf_tuning_cv = function(row){
  
  # print(c(row["min_n_param"], row["trees_param"]))
  
  training_cvs = vfold_cv(trainingdata, v = 10)
  
  
  #creating model
  rfmod_1 <- rand_forest(min_n = row["min_n_param"], trees = row["trees_param"],
                         mtry = floor(sqrt(ncol(trainingdata) - 3))) %>%
    set_engine("ranger") %>%               
    set_mode("classification")            
  
  #creating recipe
  rfrecipe_1 <- recipe(Humpback ~ ., data = trainingdata) %>%
    step_rm(Time_Start, Time_End) %>%
    step_normalize(all_numeric_predictors()) %>%
    step_dummy(all_factor_predictors())
  
  
  #creating workflow
  rfworkflow_1 <- workflow() %>%
    add_model(rfmod_1) %>%
    add_recipe(rfrecipe_1)
  
  
  # fitting model and saving cross validated predictions
  rffit_1 = rfworkflow_1 %>% 
    fit_resamples(resamples = training_cvs, 
                  control = control_resamples(save_pred = TRUE)) 
  
  
  
  
  predictions <- collect_predictions(rffit_1)
  #print(predictions)
  predictions = predictions %>% arrange(.row) %>%
    select(.row, .pred_class, Humpback)
  # print(preds)
  
  
  
  rfcvpredictions = predictions %>%
  left_join(
    trainingdata %>%
      mutate(.row = row_number()) %>%
      select(.row, Time_Start, Time_End),
    by = ".row") %>% rename(preds = .pred_class)
  
  
    return(rfcvpredictions)
}
  ##############################################################################

  
```


```{r}

grid = vec_expand_grid(min_n_param = c(100),
  trees_param = c(1, 1000))


result = apply(grid, MARGIN = 1, FUN = rf_tuning_cv)


```



```{r}
# takes inputs of a list of dataframes, and a row from the grid
calc_metrics <- function(df_list, row) {
  lapply(result, function(df) {
    print(row)

    rfcvwindowpredictions = testing_eval_windows(df, 
                                                length = row["agg_window_length"], 
                                                threshold = row["agg_window_threshold"])


    if (nrow(rfcvwindowpredictions %>% filter(prediction == 1))== 0 |
        nrow(rfcvwindowpredictions %>% filter(prediction == 0)) == 0){
      rfcv_recall = -1
      rfcv_precision = -1
      rfcv_f1 = -1
      } else {

        rfcv_recall = rfcvwindowpredictions %>% recall(truth = Humpback,
                                   estimate = prediction,
                                   event_level = 'second') %>%
              select(.estimate) %>% pull()

        rfcv_precision = rfcvwindowpredictions %>% precision(truth = Humpback,
                                   estimate = prediction,
                                   event_level = 'second') %>%
              select(.estimate) %>% pull()

        rfcv_f1 = (2*rfcv_recall*rfcv_precision)/(rfcv_recall + rfcv_precision)
      }
    # return(c("min_n_param" = row["min_n_param"],
    # "trees_param" = row["trees_param"],
    # "agg_window_length" = row["agg_window_length"],
    # "agg_window_threshold" = row["agg_window_threshold"],
    # "Recall" = rfcv_recall,
    # "Precision" = rfcv_precision,
    # "F1" = rfcv_f1))
    
    
    #truth = rfcvwindowpredictions[[]]
    
    
    # tp <- sum(truth == positive_class & pred == positive_class)
    # fp <- sum(truth != positive_class & pred == positive_class)
    # fn <- sum(truth == positive_class & pred != positive_class)
    # 
    # precision <- if ((tp + fp) == 0) NA else tp / (tp + fp)
    # recall    <- if ((tp + fn) == 0) NA else tp / (tp + fn)
    # 
    # f1.score = (2 * precision * recall)/(precision + recall)
    # 
    # data.frame(precision = precision, recall = recall, f1 = f1.score)
  })
}

grid2 = vec_expand_grid(min_n_param = c(100), trees_param = c(1, 1000),
  agg_window_length = c(1, 2),
  agg_window_threshold = c(0.5))
grid2

# calc_metrics(result, truth_col = "Humpback", pred_col = "prediction", positive_class = 1,
#              agg_window_length = 2, agg_window_threshold = 0.5)


apply(grid2, MARGIN = 1, FUN = calc_metrics, 
      df_list = result)
```



```{r}
rf_aggregation_tuning = function(result, row)
  rfcvwindowpredictions = testing_eval_windows(rfcvpredictions, 
                                                length = row["agg_window_length"], 
                                                threshold = row["agg_window_threshold"])
  
  
  if (nrow(rfcvwindowpredictions %>% filter(prediction == 1))== 0 | 
      nrow(rfcvwindowpredictions %>% filter(prediction == 0)) == 0){
    rfcv_recall = -1
    rfcv_precision = -1
    rfcv_f1 = -1
    } else {
    
      rfcv_recall = rfcvwindowpredictions %>% recall(truth = Humpback, 
                                 estimate = prediction, 
                                 event_level = 'second') %>%
            select(.estimate) %>% pull()
      
      rfcv_precision = rfcvwindowpredictions %>% precision(truth = Humpback, 
                                 estimate = prediction, 
                                 event_level = 'second') %>%
            select(.estimate) %>% pull()
      
      rfcv_f1 = (2*rfcv_recall*rfcv_precision)/(rfcv_recall + rfcv_precision)
    }
  return(c("min_n_param" = row["min_n_param"],
  "trees_param" = row["trees_param"],
  "agg_window_length" = row["agg_window_length"], 
  "agg_window_threshold" = row["agg_window_threshold"], 
  "Recall" = rfcv_recall, 
  "Precision" = rfcv_precision,
  "F1" = rfcv_f1))
```


```{r}


result[1]
result[2]
length(result)
for (i in c(1:length(result))){
  print(i)
}


for (i in c(1:2)){
  print(result[i])
}

data.frame(t(result)) %>% arrange(desc(Recall))






# rf_tuning(min_n_param = 100,
#   trees_param = 1000,
#   agg_window_length = 2, 
#   agg_window_threshold = 0.5)

# min_n, trees, length, threshold as inputs
```


```{r}

individual_calls = custom_denominator(manual_annotations, rfpredictions,
                 pred_start_time = min(rfpredictions$Time_Start), 
                 pred_end_time = max(rfpredictions$Time_End), 
                 threshold = 0.5)

output = c(row, 
           "Recall" = window_recall, 
           "Precision" = window_precision,
           "F1" = window_F1, 
           "Proportion Calls Detected" = 
             sum(individual_calls$prediction == 1)/nrow(individual_calls))

```



```{r}
grid = vec_expand_grid(agg_wind_length = 4, 
                     prop_threshold = 0.5)


rf_tuning(trainingdata = trainingdata)

result = apply(grid, MARGIN = 1, FUN = rf_tuning)
data.frame(t(result)) %>% arrange(desc(Recall))

```


## Precision-Recall Curve


```{r}
library(PRROC)
library(ggplot2)

# Example data
y_true <- c(1,0,1,1,0,0,1,0,1,0)
y_scores <- c(0.9,0.2,0.8,0.7,0.3,0.4,0.95,0.1,0.85,0.5)

# Separate scores
scores_pos <- y_scores[y_true == 1]
scores_neg <- y_scores[y_true == 0]

# Compute PR curve
pr <- pr.curve(scores.class0 = scores_pos,
               scores.class1 = scores_neg,
               curve = TRUE)

# Extract curve data
pr_df <- data.frame(
  recall = pr$curve[, 1],
  precision = pr$curve[, 2],
  threshold = pr$curve[, 3]
)

# Plot with ggplot
ggplot(pr_df, aes(x = recall, y = precision)) +
  geom_line(color = "blue", size = 1) +
  labs(title = "Precision-Recall Curve",
       x = "Recall",
       y = "Precision") +
  theme_minimal()
```



## AI Code to Expand On

```{r}


# Split data
iris_split <- initial_split(iris, prop = 0.8, strata = Species)
iris_train <- training(iris_split)
iris_test  <- testing(iris_split)

# Cross-validation
iris_folds <- vfold_cv(iris_train, v = 5, strata = Species)

# Recipe
rf_recipe <- recipe(Species ~ ., data = iris_train) %>%
  step_normalize(all_predictors())

# Random forest model (tunable mtry and min_n)
rf_model <- rand_forest(
  mtry = tune(),
  min_n = tune(),
  trees = 500
) %>%
  set_engine("ranger") %>%
  set_mode("classification")

# Workflow
rf_workflow <- workflow() %>%
  add_recipe(rf_recipe) %>%
  add_model(rf_model)

# Parameter grid
rf_grid <- grid_regular(
  mtry(range = c(1, 4)),   # number of predictors in iris
  min_n(range = c(2, 10)),
  levels = 5
)

# Tune model
rf_tuned <- tune_grid(
  rf_workflow,
  resamples = iris_folds,
  grid = rf_grid,
  metrics = metric_set(accuracy)
)

# View results
collect_metrics(rf_tuned)

# Best parameters
best_params <- select_best(rf_tuned, metric = "accuracy")
best_params

# Finalize workflow
final_rf_workflow <- finalize_workflow(rf_workflow, best_params)

# Fit final model
final_rf_fit <- fit(final_rf_workflow, data = iris_train)

# Evaluate on test set
rf_preds <- predict(final_rf_fit, iris_test) %>%
  bind_cols(iris_test)

accuracy(rf_preds, truth = Species, estimate = .pred_class)
conf_mat(rf_preds, truth = Species, estimate = .pred_class)
```



