---
title: "K Nearest Neighbors"
format: html
---




## Loading Libraries

```{r}
library(tuneR)
library(seewave)
library(tidyr)
library(dplyr)
library(readxl)
library(ggplot2)
library(ranger)
library(tidyverse)
library(tidymodels)
library(kknn)
library(discrim)
library(vctrs)
library(PRROC)
```


## Loading In Data

```{r}
data = read.csv(here::here("GrayWhaleMethod", "TrainingSet", "GrayWhaleTrainingData.csv")) %>%
  mutate(Humpback = as.factor(Humpback))

table(data$Humpback)

max(data$Time_End)
#annotatedMelAW %>% arrange(desc(Time_End))
```

## Sourcing

```{r}
source(here::here("ContextWindows", "ContextWindowFunction.R"))

```



## Creating Training Data

```{r}

trainingdata = add_observations_linear(whaledf = data,
                                start_time = 0,
                                end_time =  7199.9,
                                num_time_steps = 1, 
                                numcep = 13,
                                step_size = 0.1)




#manual_annotations = read_excel(here::here("OrigData", "AW", "AWhb.xlsx"))
```


## Creating Tuning Grid

```{r}
grid = vec_expand_grid(neighbors_param = c(1))

```

## Setting Seed for Consistent Randomization

```{r}
set.seed(521)
```

## Tuning

```{r}
knn_tuning_cv = function(neighbors_param){
  
  training_cvs = vfold_cv(trainingdata, v = 5)
  
  # creating model
  knnmod_1 <- nearest_neighbor(
    neighbors = neighbors_param,
    weight_func = "rectangular",
    dist_power = 2
  ) %>%
    set_engine("kknn") %>%
    set_mode("classification")
  
  # creating recipe
  knnrecipe_1 <- recipe(Humpback ~ ., data = trainingdata) %>%
    step_rm(Time_Start, Time_End) %>%
    step_normalize(all_numeric_predictors()) %>%
    step_dummy(all_factor_predictors())
  
  # creating workflow
  knnworkflow_1 <- workflow() %>%
    add_model(knnmod_1) %>%
    add_recipe(knnrecipe_1)
  
  # fitting model and saving cross-validated predictions
  knnfit_1 = knnworkflow_1 %>%
    fit_resamples(
      resamples = training_cvs,
      control = control_resamples(save_pred = TRUE)
    )
  
  predictions <- collect_predictions(knnfit_1)
  
  predictions = predictions %>%
    arrange(.row) %>%
    select(.row, .pred_class, Humpback)
  
  knncvpredictions = predictions %>%
    left_join(
      trainingdata %>%
        mutate(.row = row_number()) %>%
        select(.row, Time_Start, Time_End),
      by = ".row"
    ) %>%
    rename(preds = .pred_class)
  
  return(list(
    neighbors_param = neighbors_param,
    knncvpredictions = knncvpredictions
  ))
}
```

```{r}




results <- mapply(
  knn_tuning_cv,
  grid$neighbors_param,
  SIMPLIFY = FALSE
)

results

```

## Calculating Metrics


```{r}


# i is a input of a dataframe (knncvpredictions) and number of neighbors

calc_metrics <- lapply(results, function(res) {
  neighbors <- res$neighbors_param
  predictionsdf <- res$knncvpredictions
  
  if (nrow(predictionsdf %>% filter(preds == 1)) == 0) {
    knncv_recall <- 0
    knncv_precision <- NA
    
  } else if (nrow(predictionsdf %>% filter(preds == 0)) == 0) {
    knncv_recall <- 1
    knncv_precision <- nrow(predictionsdf %>% filter(Humpback == 1)) /
      nrow(predictionsdf %>% filter(preds == 1))
    
  } else if (nrow(predictionsdf %>% filter(Humpback == 1)) == 0) {
    knncv_recall <- NA
    knncv_precision <- 0
    
  } else {
    knncv_recall <- predictionsdf %>%
      recall(truth = Humpback, estimate = preds, event_level = "second") %>%
      pull(.estimate)
    
    knncv_precision <- predictionsdf %>%
      precision(truth = Humpback, estimate = preds, event_level = "second") %>%
      pull(.estimate)
  }
  
  knncv_f1 <- (2 * knncv_recall * knncv_precision) / (knncv_recall + knncv_precision)
  knncv_f2 <- (5 * knncv_recall * knncv_precision) / (knncv_recall + 4 * knncv_precision)
  
  data.frame(
    neighbors_param = neighbors,
    Recall = knncv_recall,
    Precision = knncv_precision,
    F1 = knncv_f1,
    F2 = knncv_f2
  )
})

final_df <- do.call(rbind, calc_metrics)

final_df %>% data.frame() %>% arrange(desc(Recall))

sorted_df = final_df %>% data.frame() %>% arrange(desc(F2))

sorted_df
```




## PR Curve


```{r}



sorted_df %>%
  ggplot(aes(x = Recall, y = Precision)) +
  geom_line() +
  geom_point() +
  scale_color_manual(values = c("red", "blue", "green", "yellow")) +
  scale_x_continuous(limits = c(0, 1)) +
  scale_y_continuous(limits = c(0.5, 1)) +
  labs(
    title = "Precision-Recall Curve of Different Number of Neighbors",
    x = "Recall",
    y = "Precision",
    color = "Window Length"
  ) +
  theme_minimal()
```
