---
title: "temp2"
format: html
---


## Loading Libraries

```{r}
library(tuneR)
library(seewave)
library(tidyr)
library(dplyr)
library(readxl)
library(ggplot2)
library(ranger)
library(tidyverse)
library(tidymodels)
library(kknn)
library(discrim)
library(vctrs)
```


```{r}
grid = vec_expand_grid(min_n_param = c(100, 500),
  trees_param = c(1000))

agg_window_length = c(2, 8)
#agg_window_threshold = seq(0, 1, by = 0.05)

#agg_window_length = c(2)
agg_window_threshold = c(0.5)

```




## Sourcing

```{r}
source(here::here("ContextWindows", "ContextWindowFunctions.R"))
source(here::here("EvaluationWindows", "EvaluationWindowFunctions.R"))
source(here::here("CustomDenominator.R"))
```


## Setting Seed for Consistent Randomization

```{r}
set.seed(897)
```


## Loading In Data

```{r}
data = read.csv(here::here("GrayWhaleMethod", "TrainingSet", "GrayWhaleTrainingData.csv")) %>%
  mutate(Humpback = as.factor(Humpback))

tempdata = data %>% filter(Time_Start <= 1000)


#annotatedMelAW %>% arrange(desc(Time_End))
```


## Creating Training Data

```{r}
trainingdata = add_observations(whaledf = tempdata,
                                start_time = 0,
                                end_time = 1000,
                                num_time_steps = 1, 
                                numcep = 13,
                                step_size = 0.1)

trainingdata


manual_annotations = read_excel(here::here("OrigData", "AW", "AWhb.xlsx"))
```



## Tuning

```{r}

rf_tuning_cv = function(min_n_param, trees_param){
  
  # print(c(row["min_n_param"], row["trees_param"]))
  
  training_cvs = vfold_cv(trainingdata, v = 10)
  
  #creating model
  rfmod_1 <- rand_forest(min_n = min_n_param, trees = trees_param,
                         mtry = floor(sqrt(ncol(trainingdata) - 3))) %>%
    set_engine("ranger") %>%               
    set_mode("classification")            
  
  #creating recipe
  rfrecipe_1 <- recipe(Humpback ~ ., data = trainingdata) %>%
    step_rm(Time_Start, Time_End) %>%
    step_normalize(all_numeric_predictors()) %>%
    step_dummy(all_factor_predictors())
  
  
  #creating workflow
  rfworkflow_1 <- workflow() %>%
    add_model(rfmod_1) %>%
    add_recipe(rfrecipe_1)
  
  # fitting model and saving cross validated predictions
  rffit_1 = rfworkflow_1 %>% 
    fit_resamples(resamples = training_cvs, 
                  control = control_resamples(save_pred = TRUE)) 
  
  predictions <- collect_predictions(rffit_1)
  #print(predictions)
  predictions = predictions %>% arrange(.row) %>%
    select(.row, .pred_class, Humpback)
  # print(preds)
  
  rfcvpredictions = predictions %>%
  left_join(
    trainingdata %>%
      mutate(.row = row_number()) %>%
      select(.row, Time_Start, Time_End),
    by = ".row") %>% rename(preds = .pred_class)
  
    return(list(min_n_param = min_n_param,
                trees_param = trees_param,
                rfcvpredictions = rfcvpredictions))
}
```

```{r}




results <- mapply(
  rf_tuning_cv,
  grid$min_n_param,
  grid$trees_param,
  SIMPLIFY = FALSE
)

# results
```



```{r}



grid2 <- expand.grid(
  i = seq_along(results),
  lengths = agg_window_length,
  thresholds = agg_window_threshold
)

grid2
```

```{r}

calc_metrics = mapply(function(i, lengths, thresholds){
  res = results[[i]]
  
  min_n = res$min_n_param
  trees = res$trees_param
  #print(c(min_n, trees, lengths, thresholds))
  rfcvwindowpredictions = testing_eval_windows(res$rfcvpredictions, 
                                                length = lengths, 
                                                threshold = thresholds)
  
  #print(rfcvwindowpredictions)
  
  
  # precision check
  
  if (nrow(rfcvwindowpredictions %>% filter(prediction == 1)) == 0){
    rfcv_recall = 0
    rfcv_precision = NA

    }
  
  else if (nrow(rfcvwindowpredictions %>% filter(prediction == 0)) == 0){
    rfcv_recall = 1
    rfcv_precision = (nrow(rfcvwindowpredictions %>% filter(Humpback == 1)))/nrow(rfcvwindowpredictions %>% filter(prediction == 1))

    }
  
  # recall check
  
  else if (nrow(rfcvwindowpredictions %>% filter(Humpback == 1))== 0){
    rfcv_recall = NA
    rfcv_precision = 0

    } else {
    
      rfcv_recall = rfcvwindowpredictions %>% recall(truth = Humpback, 
                                 estimate = prediction, 
                                 event_level = 'second') %>%
            select(.estimate) %>% pull()
      
      rfcv_precision = rfcvwindowpredictions %>% precision(truth = Humpback, 
                                 estimate = prediction, 
                                 event_level = 'second') %>%
            select(.estimate) %>% pull()
      
      
      
      
    }
  rfcv_f1 = (2*rfcv_recall*rfcv_precision)/(rfcv_recall + rfcv_precision)
      
  rfcv_f2 = (5*rfcv_recall*rfcv_precision)/(rfcv_recall + (4*rfcv_precision))
  
  return(c("min_n_param" = min_n,
  "trees_param" = trees,
  "agg_window_length" = lengths, 
  "agg_window_threshold" = thresholds, 
  "Recall" = rfcv_recall, 
  "Precision" = rfcv_precision,
  "F1" = rfcv_f1,
  "F2" = rfcv_f2))
  
}, grid2$i, grid2$lengths, grid2$thresholds, SIMPLIFY = FALSE)


final_df <- do.call(rbind, calc_metrics)

final_df %>% data.frame() %>% filter(agg_window_length == 8) %>% arrange(desc(Recall))

sorted_df = final_df %>% data.frame() %>% arrange(desc(F2))

sorted_df
```


## PR Curve


```{r}
library(PRROC)
library(ggplot2)


sorted_df %>%
  ggplot(aes(x = Recall, y = Precision, 
             group = agg_window_length,
             color = factor(agg_window_length))) +
  geom_line() +
  geom_point() +
  scale_color_manual(values = c("red", "blue", "green", "yellow")) +
  scale_x_continuous(limits = c(0, 1)) +
  scale_y_continuous(limits = c(0.5, 1)) +
  labs(
    title = "Precision-Recall Curve on Window Predictions",
    x = "Recall",
    y = "Precision",
    color = "Window Length"
  ) +
  theme_minimal()
```

```{r}



# Example data
y_true <- c(1,0,1,1,0,0,1,0,1,0)
y_scores <- c(0.9,0.2,0.8,0.7,0.3,0.4,0.95,0.1,0.85,0.5)

# Separate scores
scores_pos <- y_scores[y_true == 1]
scores_neg <- y_scores[y_true == 0]

# Compute PR curve
pr <- pr.curve(scores.class0 = scores_pos,
               scores.class1 = scores_neg,
               curve = TRUE)

# Extract curve data
pr_df <- data.frame(
  recall = pr$curve[, 1],
  precision = pr$curve[, 2],
  threshold = pr$curve[, 3]
)

# Plot with ggplot
ggplot(pr_df, aes(x = recall, y = precision)) +
  geom_line(color = "blue", size = 1) +
  labs(title = "Precision-Recall Curve",
       x = "Recall",
       y = "Precision") +
  theme_minimal()
```

