---
title: "K Nearest Neighbors"
format: html
---


## Loading Libraries

```{r}
library(tidyr)
library(dplyr)
library(readxl)
library(ggplot2)
library(ranger)
library(tidyverse)
library(tidymodels)
library(kknn)
library(discrim)
library(vctrs)
library(tictoc)
```


## Sourcing

```{r}
#source(here::here("EvaluationWindows", "EvaluationWindowFunctions.R"))
#source(here::here("CustomDenominator.R"))
source(here::here("ContextWindows", "AIContextWindowFunction.R"))

```


## Setting Seed for Consistent Randomization

```{r}
set.seed(197)
```


## Loading In Data

```{r}
# data = read.csv(here::here("GrayWhaleMethod", "TrainingSet", "GrayWhaleTrainingData.csv")) %>%
#   mutate(Humpback = as.factor(Humpback))

data = read.csv(here::here("TrainingSet", "annotatedMelAW2000-Training.csv")) %>%
  mutate(Humpback = as.factor(Humpback))


#annotatedMelAW %>% arrange(desc(Time_End))
```

## Entering Parameters

```{r}



grid = vec_expand_grid(neighbors_param = 1000)

num_time_steps = 40

agg_window_length = c(2)
#agg_window_threshold = seq(0, 1, by = 0.05)

#agg_window_length = c(2)
agg_window_threshold = c(0.5)

```

## Creating Training Data

```{r}




trainingdata = add_observations_linear(whaledf = data,
                                start_time = 4000,
                                end_time = 4500,
                                num_time_steps = num_time_steps, 
                                numcep = 12,
                                step_size = 0.1,
                                jump_size = 0.05)





#trainingdata

table(trainingdata$Humpback)
#table(trainingdata2$Humpback)
trainingdata$Humpback <- relevel(trainingdata$Humpback, ref = 1)
#manual_annotations = read_excel(here::here("OrigData", "AW", "AWhb.xlsx"))
```



## Tuning

```{r}
knn_tuning_cv = function(neighbors_param){
  tic("My Function Timer")

  training_cvs = vfold_cv(trainingdata, v = 5)
  
  # creating model
  knnmod_1 <- nearest_neighbor(
    neighbors = neighbors_param,
    weight_func = "rectangular",
    dist_power = 2
  ) %>%
    set_engine("kknn") %>%
    set_mode("classification")
  
  # creating recipe
  knnrecipe_1 <- recipe(Humpback ~ ., data = trainingdata) %>%
    step_rm(Time_Start, Time_End) %>%
    step_normalize(all_numeric_predictors()) %>%
    step_dummy(all_factor_predictors())
  
  # creating workflow
  knnworkflow_1 <- workflow() %>%
    add_model(knnmod_1) %>%
    add_recipe(knnrecipe_1)
  
  # fitting model and saving cross-validated predictions
  knnfit_1 = knnworkflow_1 %>%
    fit_resamples(
      resamples = training_cvs,
      control = control_resamples(save_pred = TRUE)
    )
  
  predictions <- collect_predictions(knnfit_1)
  
  predictions = predictions %>%
    arrange(.row) %>%
    select(.row, .pred_class, Humpback)
  
  knncvpredictions = predictions %>%
    left_join(
      trainingdata %>%
        mutate(.row = row_number()) %>%
        select(.row, Time_Start, Time_End),
      by = ".row"
    ) %>%
    rename(preds = .pred_class)
  toc()
  return(list(
    neighbors_param = neighbors_param,
    knncvpredictions = knncvpredictions
  ))
}
```

```{r}




results <- mapply(
  knn_tuning_cv,
  grid$neighbors_param,
  SIMPLIFY = FALSE
)

results

table(results[[1]]$knncvpredictions$Humpback)
table(results[[1]]$knncvpredictions$preds)

```

```{r}
knn_tuning_cv_multi_nopreds <- function(k_values) {
  tic("My Function Timer")
  
  training_cvs <- vfold_cv(trainingdata, v = 5)
  
  # custom metric set
  my_metrics <- metric_set(
    precision,
    recall,
    f_meas  # we'll control beta below
  )
  
  # model
  knnmod <- nearest_neighbor(
    neighbors = tune(),
    weight_func = "rectangular",
    dist_power = 2
  ) %>%
    set_engine("kknn") %>%
    set_mode("classification")
  
  # recipe
  knnrecipe <- recipe(Humpback ~ ., data = trainingdata) %>%
    step_rm(Time_Start, Time_End) %>%
    step_normalize(all_numeric_predictors()) %>%
    step_dummy(all_factor_predictors())
  
  # workflow
  knnworkflow <- workflow() %>%
    add_model(knnmod) %>%
    add_recipe(knnrecipe)
  
  # grid
  k_grid <- tibble(neighbors = k_values)
  
  # tune
  knn_tuned <- knnworkflow %>%
    tune_grid(
      resamples = training_cvs,
      grid = k_grid,
      metrics = my_metrics,
      control = control_grid(save_pred = FALSE)
    )
  
  # collect metrics (default F1)
  metrics_f1 <- collect_metrics(knn_tuned)
  
  # collect F2 separately
  metrics_f2 <- collect_metrics(knn_tuned, metric = "f_meas", beta = 2) %>%
    mutate(.metric = "f2")
  
  toc()
  
  return(list(
    k_values = k_values,
    tuning_results = knn_tuned,
    metrics_f1 = metrics_f1,
    metrics_f2 = metrics_f2
  ))
}


results <- knn_tuning_cv_multi_nopreds(c(3,5,7,9))

results$metrics_f1   # precision, recall, F1
results$metrics_f2   # F2 scores
```


```{r}



grid2 <- expand.grid(
  i = seq_along(results),
  lengths = agg_window_length,
  thresholds = agg_window_threshold
)

grid2
```







```{r}


# i is a input of a dataframe (knncvpredictions) and number of neighbors

calc_metrics <- lapply(results, function(res) {
  neighbors <- res$neighbors_param
  predictionsdf <- res$knncvpredictions
  
  if (nrow(predictionsdf %>% filter(preds == 1)) == 0) {
    knncv_recall <- 0
    knncv_precision <- NA
    
  } else if (nrow(predictionsdf %>% filter(preds == 0)) == 0) {
    knncv_recall <- 1
    knncv_precision <- nrow(predictionsdf %>% filter(Humpback == 1)) /
      nrow(predictionsdf %>% filter(preds == 1))
    
  } else if (nrow(predictionsdf %>% filter(Humpback == 1)) == 0) {
    knncv_recall <- NA
    knncv_precision <- 0
    
  } else {
    knncv_recall <- predictionsdf %>%
      recall(truth = Humpback, estimate = preds, event_level = "second") %>%
      pull(.estimate)
    
    knncv_precision <- predictionsdf %>%
      precision(truth = Humpback, estimate = preds, event_level = "second") %>%
      pull(.estimate)
  }
  
  knncv_f1 <- (2 * knncv_recall * knncv_precision) / (knncv_recall + knncv_precision)
  knncv_f2 <- (5 * knncv_recall * knncv_precision) / (knncv_recall + 4 * knncv_precision)
  
  data.frame(
    neighbors_param = neighbors,
    Recall = knncv_recall,
    Precision = knncv_precision,
    F1 = knncv_f1,
    F2 = knncv_f2
  )
})

final_df <- do.call(rbind, calc_metrics)

final_df %>% data.frame() %>% 
  mutate(Time_Steps = num_time_steps, .before = 1)%>% arrange(desc(Recall))

sorted_df = final_df %>% data.frame() %>% arrange(desc(F2))

sorted_df
```

## DONT USE


```{r}

source(here::here("EvaluationWindows", "NEWEvaluationWindowFunctions.R"))

# i is a input of a dataframe (knncvpredictions) and number of neighbors
# lengths is a number
# thresholds is a number

calc_metrics = mapply(function(i, lengths, thresholds){
  res = results[[i]]
  
  neighbors = res$neighbors_param

  # rfcvwindowpredictions = testing_eval_windows(res$rfcvpredictions,
  #                                               length = lengths,
  #                                               threshold = thresholds)
  
  
  knncvwindowpredictions = testing_eval_windows_linear(res$knncvpredictions,
                                                length = lengths,
                                                threshold = thresholds)

  #print(rfcvwindowpredictions)
  
  
  # precision check
  
  if (nrow(knncvwindowpredictions %>% filter(prediction == 1)) == 0){
    knncv_recall = 0
    knncv_precision = NA

    }
  
  else if (nrow(knncvwindowpredictions %>% filter(prediction == 0)) == 0){
    knncv_recall = 1
    knncv_precision = (nrow(knncvwindowpredictions %>% filter(Humpback == 1)))/nrow(knncvwindowpredictions %>% filter(prediction == 1))

    }
  
  # recall check
  
  else if (nrow(knncvwindowpredictions %>% filter(Humpback == 1))== 0){
    knncv_recall = NA
    knncv_precision = 0

    } else {
    
      knncv_recall = knncvwindowpredictions %>% recall(truth = Humpback, 
                                 estimate = prediction, 
                                 event_level = 'second') %>%
            select(.estimate) %>% pull()
      
      knncv_precision = knncvwindowpredictions %>% precision(truth = Humpback, 
                                 estimate = prediction, 
                                 event_level = 'second') %>%
            select(.estimate) %>% pull()
      
      
      
      
    }
  knncv_f1 = (2*knncv_recall*knncv_precision)/(knncv_recall + knncv_precision)
      
  knncv_f2 = (5*knncv_recall*knncv_precision)/(knncv_recall + (4*knncv_precision))
  
  return(c("neighbors_param" = neighbors,
  "agg_window_length" = lengths, 
  "agg_window_threshold" = thresholds, 
  "Recall" = knncv_recall, 
  "Precision" = knncv_precision,
  "F1" = knncv_f1,
  "F2" = knncv_f2))
  
}, grid2$i, grid2$lengths, grid2$thresholds, SIMPLIFY = FALSE)


final_df <- do.call(rbind, calc_metrics)

final_df %>% data.frame() %>% arrange(desc(Recall))

sorted_df = final_df %>% data.frame() %>% arrange(desc(F2))

sorted_df
```


```{r}
library(dplyr)
library(purrr)
library(yardstick)

calc_metrics_fast <- function(grid2, results) {
  
  # cache for testing_eval_windows_linear outputs
  window_cache <- new.env(parent = emptyenv())
  
  get_window_predictions <- function(i, lengths, thresholds) {
    key <- paste(i, lengths, thresholds, sep = "_")
    
    if (!exists(key, envir = window_cache, inherits = FALSE)) {
      res <- results[[i]]
      window_cache[[key]] <- testing_eval_windows_linear(
        res$knncvpredictions,
        length = lengths,
        threshold = thresholds
      )
    }
    
    window_cache[[key]]
  }
  
  calc_one <- function(i, lengths, thresholds) {
    res <- results[[i]]
    neighbors <- res$neighbors_param
    
    knncvwindowpredictions <- get_window_predictions(i, lengths, thresholds)
    
    n_pred_1 <- sum(knncvwindowpredictions$prediction == 1)
    n_pred_0 <- sum(knncvwindowpredictions$prediction == 0)
    n_true_1 <- sum(knncvwindowpredictions$Humpback == 1)
    
    if (n_pred_1 == 0) {
      knncv_recall <- 0
      knncv_precision <- NA_real_
      
    } else if (n_pred_0 == 0) {
      knncv_recall <- 1
      knncv_precision <- n_true_1 / n_pred_1
      
    } else if (n_true_1 == 0) {
      knncv_recall <- NA_real_
      knncv_precision <- 0
      
    } else {
      knncv_recall <- knncvwindowpredictions %>%
        recall(truth = Humpback, estimate = prediction, event_level = "second") %>%
        pull(.estimate)
      
      knncv_precision <- knncvwindowpredictions %>%
        precision(truth = Humpback, estimate = prediction, event_level = "second") %>%
        pull(.estimate)
    }
    
    knncv_f1 <- (2 * knncv_recall * knncv_precision) / (knncv_recall + knncv_precision)
    knncv_f2 <- (5 * knncv_recall * knncv_precision) / (knncv_recall + 4 * knncv_precision)
    
    tibble(
      neighbors_param = neighbors,
      agg_window_length = lengths,
      agg_window_threshold = thresholds,
      Recall = knncv_recall,
      Precision = knncv_precision,
      F1 = knncv_f1,
      F2 = knncv_f2
    )
  }
  
  bind_rows(
    pmap(
      list(grid2$i, grid2$lengths, grid2$thresholds),
      calc_one
    )
  )
}

final_df2 <- calc_metrics_fast(grid2, results)
sorted_df2 <- final_df2 %>% arrange(desc(F2)) %>% data.frame()
sorted_df2

all.equal(sorted_df, sorted_df2)
list(sorted_df, sorted_df2)

class(data.frame(sorted_df2))
```

## END OF DONT USE

## PR Curve


```{r}
library(PRROC)
library(ggplot2)


sorted_df %>%
  ggplot(aes(x = Recall, y = Precision, 
             group = agg_window_length,
             color = factor(agg_window_length))) +
  geom_line() +
  geom_point() +
  scale_color_manual(values = c("red", "blue", "green", "yellow")) +
  scale_x_continuous(limits = c(0, 1)) +
  scale_y_continuous(limits = c(0.5, 1)) +
  labs(
    title = "Precision-Recall Curve on Window Predictions",
    x = "Recall",
    y = "Precision",
    color = "Window Length"
  ) +
  theme_minimal()
```

```{r}



# Example data
y_true <- c(1,0,1,1,0,0,1,0,1,0)
y_scores <- c(0.9,0.2,0.8,0.7,0.3,0.4,0.95,0.1,0.85,0.5)

# Separate scores
scores_pos <- y_scores[y_true == 1]
scores_neg <- y_scores[y_true == 0]

# Compute PR curve
pr <- pr.curve(scores.class0 = scores_pos,
               scores.class1 = scores_neg,
               curve = TRUE)

# Extract curve data
pr_df <- data.frame(
  recall = pr$curve[, 1],
  precision = pr$curve[, 2],
  threshold = pr$curve[, 3]
)

# Plot with ggplot
ggplot(pr_df, aes(x = recall, y = precision)) +
  geom_line(color = "blue", size = 1) +
  labs(title = "Precision-Recall Curve",
       x = "Recall",
       y = "Precision") +
  theme_minimal()
```



```{r}
create_df <- function(n) {
  rows <- vector("list", n)
  
  for (i in 1:n) {
    rows[[i]] <- data.frame(
      id = i,
      value = i^2
    )
  }
  
  result <- do.call(rbind, rows)
  return(result)
}


create_df(5)
```


## Create Output For Raven Visualization


```{r}
knntestingoutput = knnwindowpredictions %>% 
  dplyr::select(Time_Start, Time_End, Humpback, prediction)




#creating dummy low and high frequencies for now

knntestingoutput = knntestingoutput %>% mutate(low = rep(0, times = nrow(knntestingoutput)),
                         high = rep(1000, times = nrow(knntestingoutput)))



knntestingoutput = knntestingoutput %>% filter(prediction == 1) %>% 
  rename("Begin Time (s)" = Time_Start, "End Time (s)" = Time_End, 
         "Low Freq (Hz)" = low, "High Freq (Hz)" = high) %>% 
  dplyr::select(c("Begin Time (s)", "End Time (s)", 
                  "Low Freq (Hz)", "High Freq (Hz)"))



#create output 
write.table(knntestingoutput, "knnevalwindowpreds.txt", sep = "\t", row.names = FALSE, quote = FALSE)
```
