---
title: "NEW KNN Tuning"
format: html
editor: source
---




## Loading Libraries

```{r}
library(tuneR)
library(seewave)
library(tidyr)
library(dplyr)
library(readxl)
library(ggplot2)
library(ranger)
library(tidyverse)
library(tidymodels)
library(kknn)
library(discrim)
library(vctrs)
```

## Sourcing

```{r}
source(here::here("ContextWindows", "ContextWindowFunctions.R"))
source(here::here("EvaluationWindowFunctions.R"))
source(here::here("CustomDenominator.R"))
```


## Setting Seed for Consistent Randomization

```{r}
set.seed(561)
```


## Loading in Data


```{r}
data = read.csv(here::here("annotatedmelAWFull2000-1.csv"))

```


## Creating Training Data

```{r}
mel_data = add_observations(whaledf = data,
                                start_time = 0,
                                end_time = 250,
                                num_time_steps = 40, 
                                numcep = 12,
                                step_size = 0.05)

# remove coefficients based on num time_steps

```


## Function

```{r}
knn_tuning = function(row, start, end, mel_data, manual_annotations){
  
  # using training data only within the specified time range
  trainingdata = mel_data %>% filter(start <= Time_Start & Time_Start <= end)
  
  # filtering the data based on the number of time steps
  suffix <- as.numeric(sub(".*?(\\d+)$", "\\1", names(trainingdata)))

  trainingdata = trainingdata %>% 
    select(all_of(names(trainingdata)[is.na(suffix) | suffix <= row["num_time_steps"]]))
  
  print(trainingdata)
  
  print(sum(is.na(trainingdata)))
  
  # balancing data, if requested
  if (row["balanced"] == TRUE){
  
    numnegatives = nrow(trainingdata %>% filter(Humpback == 0))
    
    numpositives = nrow(trainingdata %>% filter(Humpback == 1))

    # taking row numbers of negative observations
    trainingnegatives = trainingdata %>% filter(Humpback == 0)

    # taking row numbers of positive observations
    trainingpositives = trainingdata %>% filter(Humpback == 1)
  
    trainingdata = rbind(trainingnegatives[sample(c(1:nrow(trainingnegatives)), size = min(numnegatives, numpositives)),],
                                trainingpositives[sample(c(1:nrow(trainingpositives)), size = min(numnegatives, numpositives)),]
                                    )
  }
  
  #print(table(trainingdata$Humpback))
  training_cvs = vfold_cv(trainingdata, v = 10)
  
  
  #creating model
  knn_mod1 = nearest_neighbor(neighbors = row["num_neighbors"]) %>%
    set_engine("kknn") %>%
    set_mode("classification")
  
  #creating recipe
  knnrecipe_1 = recipe(Humpback ~ ., data = trainingdata) %>%
    step_rm(Time_Start, Time_End) %>%
    step_normalize(all_numeric_predictors()) %>%
    step_dummy(all_factor_predictors())
  
  
  #creating workflow
  knnworkflow_1 = workflow() %>% 
    add_recipe(knnrecipe_1) %>% 
    add_model(knn_mod1)
  
  # saving cross validated predictions
  ctrl <- control_resamples(save_pred = TRUE)
  
  # fitting model
  knnfit_1 = knnworkflow_1 %>% 
    fit_resamples(trainingdata, resamples = training_cvs, control = ctrl) 

  predictions <- collect_predictions(knnfit_1)
  #print(predictions)
  predictions = predictions %>% arrange(.row) %>% select(.row, .pred_class, Humpback)
  # print(preds)
  
  knnpredictions <- predictions %>%
  left_join(
    mel_data %>%
      mutate(.row = row_number()) %>%
      select(.row, Time_Start, Time_End),
    by = ".row") %>% rename(preds = .pred_class)
  #print(knnpredictions)
  
  
  
  # knnpredictions = testingdata %>%
  # mutate(
  #   preds = predict(knnfit_1, testingdata)$.pred_class
  # ) %>% dplyr::select(Time_Start, Time_End, preds, Humpback)

  
  knnwindowpredictions = testing_eval_windows(knnpredictions, 
                                              length = row["agg_wind_length"], 
                                              threshold = row["prop_threshold"])
  
  #knnwindowpredictions
  
  # knnwindowpredictions %>%
  #   conf_mat(truth = Humpback,
  #            estimate = prediction)
  
  
  if (nrow(knnwindowpredictions %>% filter(prediction == 1))== 0 | 
      nrow(knnwindowpredictions %>% filter(prediction == 0)) == 0){
    window_recall = -1
    window_precision = -1
    window_F1 = -1
    
  } else {
    window_recall = knnwindowpredictions %>% 
      recall(truth = Humpback, estimate = prediction, event_level = 'second') %>%
      select(.estimate) %>% pull()
    
    window_precision = knnwindowpredictions %>% 
      precision(truth = Humpback, estimate = prediction, event_level = 'second') %>%
      select(.estimate) %>% pull()
   
    window_F1 = (2 * window_recall * window_precision)/(window_recall + window_precision)
  
  
  }
  


  individual_calls = custom_denominator(manual_annotations, knnpredictions,
                   pred_start_time = min(knnpredictions$Time_Start),
                   pred_end_time = max(knnpredictions$Time_End),
                   threshold = 0.5)

  output = c(row,
             "Recall" = window_recall,
             "Precision" = window_precision,
             "F1" = window_F1,
             "proportion of calls detected" = sum(individual_calls$prediction == 1)/nrow(individual_calls))
  print(class(output))
  return(output)
}


# knn_tuning(num_time_steps = 20, agg_wind_length = 1, 
#                      prop_threshold = 0.5, balanced = TRUE)



```


## Running Function


```{r}
grid = vec_expand_grid(num_time_steps = c(20, 40), 
                       num_neighbors = c(100, 200), 
                      agg_wind_length = c(5, 10), 
                     prop_threshold = c(0.5), 
                     balanced = c(FALSE))

# unbalanced data appears to be better

result = apply(grid, MARGIN = 1, FUN = knn_tuning, 
               mel_data = mel_data, start = 0, end = 250,
               manual_annotations = read_excel(here::here("TrainingData", "AW", "AWhb.xlsx")))
data.frame(t(result)) %>% arrange(desc(Recall))

```



```{r}
df <- data.frame(
  var1_100 = 1:5,
  var2_3948 = 6:10,
  var10_1 = 11:15,
  var20_5 = 16:20
)


threshold <- 10

suffix <- as.numeric(sub(".*?(\\d+)$", "\\1", names(df)))

df_filtered <- df %>%
  select(all_of(names(df)[is.na(suffix) | suffix >= threshold]))

df %>%
  select(all_of(names(df)[is.na(suffix) | suffix < threshold]))

```

