---
title: "Random Forest Model Tuning"
format: html
editor: source
---


- function for specifying context window length (num_time_steps), aggregation length, and threshold link

- then compare recall, F2, and how many whales are correctly predicted

- start with 2 each, create data frame of all combinations and pass it through the function


## Loading Libraries

```{r}
library(tuneR)
library(seewave)
library(tidyr)
library(dplyr)
library(readxl)
library(ggplot2)
library(ranger)
library(tidyverse)
library(tidymodels)
library(kknn)
library(discrim)
library(vctrs)
```

## Sourcing

```{r}
source(here::here("ContextWindows", "ContextWindowFunctions.R"))
source(here::here("EvaluationWindowFunctions.R"))
source(here::here("CustomDenominator.R"))
```


## Setting Seed for Consistent Randomization

```{r}
set.seed(716)
```


## Loading In Data

```{r}
data = read.csv(here::here("annotatedmelAW.csv"))

# data = read.csv(here::here("60minutes.csv"))

# data = read.csv(here::here("FullMelAW.csv"))

#annotatedMelAW = read.csv(here::here("annotatedmelAWlowerhzoverlap.csv"))
# first 30 minutes is in this data set

#annotatedMelAW %>% arrange(desc(Time_End))
```


## Function

```{r}
rf_tuning = function(row){
  
  if (row["balanced"] == FALSE){
    trainingdata = add_observations(whaledf = data,
                                start_time = 0,
                                end_time = 200,
                                num_time_steps = row["num_time_steps"], 
                                numcep = 12,
                                step_size = 0.05)
  }
  
  if (row["balanced"] == TRUE){
    trainingdata = add_observations(whaledf = data,
                                start_time = 0,
                                end_time = 200,
                                num_time_steps = row["num_time_steps"], 
                                numcep = 12,
                                step_size = 0.05)

    numnegatives = nrow(trainingdata %>% filter(Humpback == 0))
  
    # taking row numbers of positive observations
  
    trainingpositives = trainingdata %>% filter(Humpback == 1)
  
    #trainingpositives[sample(c(1:nrow(trainingpositives)), size = numnegatives),]
  
  
    trainingdata = rbind(trainingdata %>% filter(Humpback == 0),
                                trainingpositives[sample(c(1:nrow(trainingpositives)), size = numnegatives),]
                                    )
  }
  
  testingdata = add_observations(whaledf = data,
                                start_time = 1000,
                                end_time = 1200,
                                num_time_steps = row["num_time_steps"], 
                                numcep = 12,
                                step_size = 0.05)
  
  training_cvs = vfold_cv(trainingdata, v = 10)
  
  
  rfmod_1 <- rand_forest(min_n = 100, trees = 2000,
                       mtry = floor(sqrt(ncol(trainingdata) - 3))) %>%
  set_engine("ranger") %>%               
  set_mode("classification")            

  #creating recipe
  rfrecipe_1 <- recipe(Humpback ~ ., data = trainingdata) %>%
    step_rm(Time_Start, Time_End) %>%
    step_normalize(all_numeric_predictors()) %>%
    step_dummy(all_factor_predictors())
  
  
  #creating workflow
  rfworkflow_1 <- workflow() %>%
    add_model(rfmod_1) %>%
    add_recipe(rfrecipe_1)
  
  
  #fitting model
  rffit_1 <- rfworkflow_1 %>% fit(data = trainingdata)
  
  rfpredictions = testingdata %>%
  mutate(
    preds = predict(rffit_1, testingdata)$.pred_class
  ) %>% dplyr::select(Time_Start, Time_End, preds, Humpback)

  
  rfwindowpredictions = testing_eval_windows(rfpredictions, 
                                             length = row["aggregation_window_length"], 
                                             threshold = row["prop_threshold"])
  
  rfwindowpredictions
  
  # rfwindowpredictions %>%
  #   conf_mat(truth = Humpback,
  #            estimate = prediction)
  
  
  if (nrow(rfwindowpredictions %>% filter(prediction == 1))== 0 | 
      nrow(rfwindowpredictions %>% filter(prediction == 0)) == 0){
    window_preds = 100
    
  } else {
    window_preds = rfwindowpredictions %>% 
      recall(truth = Humpback, estimate = prediction, event_level = 'second') %>%
      select(.estimate) %>% pull()
  
  }
 
  
  manual_annotations = read_excel(here::here("TrainingData", "AW", "AWhb.xlsx"))

  individual_calls = custom_denominator(manual_annotations, rfpredictions,
                   pred_start_time = min(rfpredictions$Time_Start), 
                   pred_end_time = max(rfpredictions$Time_End), 
                   threshold = 0.5)
  
  output = c(row, 
             "aggregation window recall" = window_preds, 
             "proportion of calls detected" = sum(individual_calls$prediction == 1)/nrow(individual_calls))
  print(class(output))
  return(output)
}


# rf_tuning(num_time_steps = 20, aggregation_window_length = 1, 
#                      prop_threshold = 0.5, balanced = TRUE)



```


```{r}
grid = vec_expand_grid(num_time_steps = c(20), aggregation_window_length = 1, 
                     prop_threshold = c(0.5), balanced = c(TRUE))



result = apply(grid, MARGIN = 1, FUN = rf_tuning)
data.frame(t(result))

```


```{r}
# Sample data frame
df <- data.frame(a = c(1, 2, 3), b = c(4, 5, 6))
class(df)
dim(df)

# Custom function that takes a row (vector) as input
my_function <- function(row) {
  result <- row["a"] + row["b"]
  result2 = row["a"] - row["b"]
  return(c(result, result2))
}

# Apply the function row-wise (MARGIN = 1)
apply(df, MARGIN = 1, FUN = my_function)


(c("apple" = 1,"banana" = 2))

t(c("apple" = 1,"banana" = 2))

```


```{r}
data.frame("a" = as.factor(c(1,0,1,0,1)), "b" = as.factor(c(0,0,0,0,0))) %>% recall(truth = a, estimate = b, event_level = 'second')
```

