---
title: "Gray Whale Tuning"
format: html
editor: source
---




## Loading Libraries

```{r}
library(tuneR)
library(seewave)
library(tidyr)
library(dplyr)
library(readxl)
library(ggplot2)
library(ranger)
library(tidyverse)
library(tidymodels)
library(kknn)
library(discrim)
library(vctrs)
```

## Sourcing

```{r}
source(here::here("ContextWindows", "ContextWindowFunctions.R"))
source(here::here("EvaluationWindowFunctions.R"))
source(here::here("CustomDenominator.R"))
```


## Setting Seed for Consistent Randomization

```{r}
set.seed(897)
```


## Loading In Data

```{r}
data = read.csv(here::here("GrayWhaleMethod", "graywhalemethod.csv"))

# data = read.csv(here::here("60minutes.csv"))

# data = read.csv(here::here("FullMelAW.csv"))

#annotatedMelAW = read.csv(here::here("annotatedmelAWlowerhzoverlap.csv"))
# first 30 minutes is in this data set

#annotatedMelAW %>% arrange(desc(Time_End))
```






## Function

```{r}
rf_tuning = function(row){
  
  if (row["balanced"] == FALSE){
    trainingdata = data %>% filter(Time_Start <= 500) %>% 
      mutate(Humpback = as.factor(Humpback))
  }
  
  if (row["balanced"] == TRUE){
    trainingdata = data %>% filter(Time_Start <= 500) %>% 
      mutate(Humpback = as.factor(Humpback))

    numnegatives = nrow(trainingdata %>% filter(Humpback == 0))
  
    # taking row numbers of positive observations
  
    trainingpositives = trainingdata %>% filter(Humpback == 1)
  
    #trainingpositives[sample(c(1:nrow(trainingpositives)), size = numnegatives),]
  
  
    trainingdata = rbind(trainingdata %>% 
                           filter(Humpback == 0), 
                         trainingpositives[sample(c(1:nrow(trainingpositives)), 
                                                  size = numnegatives),])
  }
  
  testingdata = data %>% filter(Time_Start < 1000 & Time_Start >= 500.1) %>% 
    mutate(Humpback = as.factor(Humpback))
  
  training_cvs = vfold_cv(trainingdata, v = 10)
  
  
  #creating model
  rfmod_1 <- rand_forest(min_n = 100, trees = 1000,
                         mtry = floor(sqrt(ncol(trainingdata) - 3))) %>%
    set_engine("ranger") %>%               
    set_mode("classification")            
  
  #creating recipe
  rfrecipe_1 <- recipe(Humpback ~ ., data = trainingdata) %>%
    step_rm(Time_Start, Time_End, X) %>%
    step_normalize(all_numeric_predictors()) %>%
    step_dummy(all_factor_predictors())
  
  
  #creating workflow
  rfworkflow_1 <- workflow() %>%
    add_model(rfmod_1) %>%
    add_recipe(rfrecipe_1)
  
  
  
  #fitting model
  rffit_1 <- rfworkflow_1 %>% fit(data = trainingdata)
  
  
  #predicting on testing data
  rfpredictions = testingdata %>%
  mutate(
    preds = predict(rffit_1, testingdata)$.pred_class
  ) %>% dplyr::select(Time_Start, Time_End, preds, Humpback)

  
  rfwindowpredictions = testing_eval_windows(rfpredictions, 
                                             length = row["agg_wind_length"], 
                                             threshold = row["prop_threshold"])
  
  
  # rfwindowpredictions %>%
  #   conf_mat(truth = Humpback,
  #            estimate = prediction)
  
  
  if (nrow(rfwindowpredictions %>% filter(prediction == 1))== 0 | 
      nrow(rfwindowpredictions %>% filter(prediction == 0)) == 0){
    window_recall = -1
    windpw_precision = -1
    window_F1 = -1
    
  } else {
    window_recall = rfwindowpredictions %>% 
      recall(truth = Humpback, estimate = prediction, event_level = 'second') %>%
      select(.estimate) %>% pull()
    
    window_precision = rfwindowpredictions %>% 
      precision(truth = Humpback, estimate = prediction, event_level = 'second') %>%
      select(.estimate) %>% pull()
    
    window_F1 = (2 * window_recall * window_precision)/(window_recall + window_precision)
  
  }
 
  
  manual_annotations = read_excel(here::here("TrainingData", "AW", "AWhb.xlsx"))

  individual_calls = custom_denominator(manual_annotations, rfpredictions,
                   pred_start_time = min(rfpredictions$Time_Start), 
                   pred_end_time = max(rfpredictions$Time_End), 
                   threshold = 0.5)
  
  output = c(row, 
             "Recall" = window_recall, 
             "Precision" = window_precision,
             "F1" = window_F1, 
             "Proportion Calls Detected" = 
               sum(individual_calls$prediction == 1)/nrow(individual_calls))
  
  print(class(output))
  return(output)
}

```



```{r}
grid = vec_expand_grid(agg_wind_length = c(1, 4, 10), 
                     prop_threshold = c(0.5), 
                     balanced = c(TRUE, FALSE))



result = apply(grid, MARGIN = 1, FUN = rf_tuning)
data.frame(t(result)) %>% arrange(desc(Recall))

```