---
title: "KNN Final Model Evaluation"
format: html
---


## Loading Libraries

```{r}
library(tuneR)
library(seewave)
library(tidyr)
library(dplyr)
library(readxl)
library(ggplot2)
library(ranger)
library(tidyverse)
library(tidymodels)
library(kknn)
library(discrim)
library(purrr)
library(yardstick)
```


## Sourcing

```{r}
source(here::here("ContextWindows", "ContextWindowFunction.R"))
source(here::here("EvaluationWindows", "RollingAverage.R"))
source(here::here("TestingPredictionIntervals.R"))
```


## Loading In Data

```{r}
data_train = read.csv(here::here("GrayWhaleMethod", 
                                 "TrainingSet", 
                                 "GrayWhaleTrainingData.csv")) %>% 
  mutate(Humpback = as.factor(Humpback))


data_test = read.csv(here::here("GrayWhaleMethod", 
                                "EvaluationSet",
                                "GrayWhaleEvaluationData.csv")) %>%
  mutate(Humpback = as.factor(Humpback))


#annotatedMelAW %>% arrange(desc(Time_End))
```




## Creating Training Data

```{r}

trainingdata = add_observations_linear(whaledf = data_train,
                                start_time = 0,
                                end_time =  7199.9,
                                num_time_steps = 1, 
                                numcep = 13,
                                step_size = 0.1)




table(trainingdata$Humpback)

```

## Creating Testing Data


```{r}
testingdata = add_observations_linear(whaledf = data_test,
                                start_time = 7200,
                                end_time =  max(data_test$Time_End),
                                num_time_steps = 1, 
                                numcep = 13,
                                step_size = 0.1)

testingdata

table(testingdata$Humpback)
```


## Loading in Annotations

```{r}
manual_annotations_evaluation = 
  read_excel(here::here("OrigData", "AW", "AWhb.xlsx")) %>% 
    rename(Begin_Time = 'Begin Time (s)', End_Time = 'End Time (s)') %>%
  filter(Begin_Time >= min(testingdata$Time_Start) & End_Time <= max(testingdata$Time_End))
```



## Creating Final Model

```{r}
# TEMP NEIGHBORS VALUE
neighbors_param = 75

# creating model
knnmod_1 <- nearest_neighbor(
  neighbors = neighbors_param,
  weight_func = "rectangular",
  dist_power = 2
) %>%
  set_engine("kknn") %>%
  set_mode("classification")

# creating recipe
knnrecipe_1 <- recipe(Humpback ~ ., data = trainingdata) %>%
  step_rm(Time_Start, Time_End) %>%
  step_normalize(all_numeric_predictors()) %>%
  step_dummy(all_factor_predictors())

# creating workflow
knnworkflow_1 <- workflow() %>%
  add_model(knnmod_1) %>%
  add_recipe(knnrecipe_1)

# fitting model
knnfit_1 = knnworkflow_1 %>%
  fit(trainingdata)
```




## Predicting on Testing Data


```{r}
predictionsdf = testingdata %>% mutate(preds = predict(knnfit_1, testingdata)$.pred_class)
# each run takes ~ 4 minutes
table(predictionsdf$preds)
```


## Creating Aggregation Grid

```{r}
# agg_window_length = c(1, 2, 4, 6, 8)
# agg_window_threshold = seq(0.00, 0.5, by = 0.05)

# for individual rows
agg_window_length = c(1)
agg_window_threshold = c(0.5)

```


```{r}



grid <- expand.grid(
  lengths = agg_window_length,
  thresholds = agg_window_threshold
)

grid

```



## Metrics Type 1

```{r}
whale_call_metrics_type1 <- function(row, predictionsdf) {
  agg_window_length <- as.numeric(row[1])
  agg_window_threshold <- as.numeric(row[2])

  rolling_average <- rolling_avg_df(
    predictionsdf,
    agg_window_length,
    agg_window_threshold
  )
  
  print(rolling_average)
    
  if (nrow(rolling_average %>% filter(rolling_avg_prediction == 1)) == 0) {
    knneval_recall <- 0
    knneval_precision <- NA
    
  } else if (nrow(rolling_average %>% filter(rolling_avg_prediction == 0)) == 0) {
    knneval_recall <- 1
    knneval_precision <- nrow(rolling_average %>% filter(Humpback == '1')) /
      nrow(rolling_average %>% filter(rolling_avg_prediction == 1))
    
  } else if (nrow(rolling_average %>% filter(Humpback == '1')) == 0) {
    knneval_recall <- NA
    knneval_precision <- 0
    
  } else {
    knneval_recall <- rolling_average %>%
      recall(truth = Humpback, estimate = rolling_avg_prediction, event_level = "second") %>%
      pull(.estimate)
    
    knneval_precision <- rolling_average %>%
      precision(truth = Humpback, estimate = rolling_avg_prediction, event_level = "second") %>%
      pull(.estimate)
  }
  
  knneval_f1 <- (2 * knneval_recall * knneval_precision) / (knneval_recall + knneval_precision)
  knneval_f2 <- (5 * knneval_recall * knneval_precision) / (knneval_recall + 4 * knneval_precision)
  
  data.frame(
    agg_window_length = agg_window_length,
    agg_window_threshold = agg_window_threshold,
    Recall = knneval_recall,
    Precision = knneval_precision,
    F1 = knneval_f1,
    F2 = knneval_f2
  )
}


final_df <- do.call(
  rbind,
  lapply(seq_len(nrow(grid)), function(i) {
    whale_call_metrics_type1(grid[i, ], predictionsdf)
  })
)

final_df
```



## PR Curve Type 1


```{r}



final_df %>%
  ggplot(aes(x = Recall, y = Precision, color = as.factor(agg_window_length), group = as.factor(agg_window_length))) +
  geom_line() +
  geom_point() +
  scale_color_manual(values = c("red", "blue", "green", "yellow", "orange", "purple")) +
  scale_x_continuous(limits = c(0, 1)) +
  scale_y_continuous(limits = c(0.5, 1)) +
  labs(
    title = "Precision-Recall Curve of Different Window Lengths and Thresholds
Individual Windows",
    x = "Recall",
    y = "Precision",
    color = "Window Length"
  ) +
  theme_minimal()
```

## Metrics Type 2


```{r}
whale_call_metrics_type2 <- function(row, predictionsdf) {
  agg_window_length <- as.numeric(row[1])
  agg_window_threshold <- as.numeric(row[2])

  rolling_average <- rolling_avg_df(
    predictionsdf,
    agg_window_length,
    agg_window_threshold
  )

  prediction_windows <- creating_prediction_windows(
    rolling_average,
    time_start = Time_Start,
    time_end = Time_End,
    value_col = rolling_avg_prediction
  )

  conf_matrix_table <- confusion_from_intervals(
    data_true = manual_annotations_evaluation,
    data_pred = prediction_windows,
    true_interval_start = Begin_Time,
    true_interval_end = End_Time,
    pred_interval_start = start_time,
    pred_interval_end = end_time
  )

  TP <- conf_matrix_table %>% dplyr::pull(TP)
  FN <- conf_matrix_table %>% dplyr::pull(FN)
  FP <- conf_matrix_table %>% dplyr::pull(FP)

  num_pred_windows <- nrow(prediction_windows)

  if (TP + FN == 0) {
    recall <- NA_real_
  } else {
    recall <- TP / (TP + FN)
  }

  if (TP + FP == 0) {
    precision <- NA_real_
  } else {
    precision <- TP / (TP + FP)
  }

  if (is.na(recall) || is.na(precision) || (recall + precision == 0)) {
    F1 <- NA_real_
  } else {
    F1 <- 2 * recall * precision / (recall + precision)
  }

  if (is.na(recall) || is.na(precision) || (4 * precision + recall == 0)) {
    F2 <- NA_real_
  } else {
    F2 <- 5 * precision * recall / (4 * precision + recall)
  }

  data.frame(
    agg_window_length = agg_window_length,
    agg_window_threshold = agg_window_threshold,
    num_pred_windows = num_pred_windows,
    Recall = recall,
    Precision = precision,
    F1 = F1,
    F2 = F2
  )
}

final_df_type2 <- do.call(
  rbind,
  lapply(seq_len(nrow(grid)), function(i) {
    whale_call_metrics_type2(grid[i, ], predictionsdf)
  })
)


sorted_df_type2 = final_df_type2 %>% data.frame() %>% arrange(desc(F2))

sorted_df_type2

manual_annotations_evaluation
```


## PR Curve Type 2



```{r}



sorted_df_type2 %>%
  ggplot(aes(x = Recall, y = Precision, color = as.factor(agg_window_length), group = as.factor(agg_window_length))) +
  geom_line() +
  geom_point() +
  scale_color_manual(values = c("red", "blue", "green", "yellow", "orange", "purple")) +
  scale_x_continuous(limits = c(0, 1)) +
  scale_y_continuous(limits = c(0.5, 1)) +
  labs(
    title = "Precision-Recall Curve of Different Window Lengths and Thresholds
Aggregated Windows",
    x = "Recall",
    y = "Precision",
    color = "Window Length"
  ) +
  theme_minimal()
```



## Saving Predictions of Best Parameters


```{r}
agg_window_length_best = 1
agg_window_threshold_best = 0.5

rolling_average_best <- rolling_avg_df(
  predictionsdf,
  agg_window_length_best,
  agg_window_threshold_best
)

prediction_windows_best <- creating_prediction_windows(
  rolling_average_best,
  time_start = Time_Start,
  time_end = Time_End,
  value_col = rolling_avg_prediction
)

prediction_windows_best
```

## Saving Output To Raven


```{r}

raven_output = function(windows){
  print(windows)
  #creating dummy low and high frequencies
  windows = windows %>% 
    rename("Begin Time (s)" = start_time, "End Time (s)" = end_time) %>% 
    mutate("Low Freq (Hz)" = 0, "High Freq (Hz)" = 2000) %>% 
    dplyr::select(c("Begin Time (s)", "End Time (s)", 
                    "Low Freq (Hz)", "High Freq (Hz)"))
  
  
  #create output 
  write.table(windows, 
              paste0("graywhalemethodknnevalwindowpreds", 
                     "len", agg_window_length_best, 
                     "thres", agg_window_threshold_best,
                     ".txt"), 
              sep = "\t", row.names = FALSE, quote = FALSE)
}

raven_output(windows = prediction_windows_best)

```
