---
title: "Random Forest"
format: html
editor: source
---





## Loading Libraries

```{r}
library(tuneR)
library(seewave)
library(tidyr)
library(dplyr)
library(readxl)
library(ggplot2)
library(ranger)
library(tidyverse)
library(tidymodels)
library(discrim)
library(randomForest)
```

## Sourcing

```{r}
source(here::here("ContextWindows", "ContextWindowFunctions.R"))
source(here::here("EvaluationWindowFunctions.R"))
source(here::here("CustomDenominator.R"))
```


## Loading In Data

```{r}
data = read.csv(here::here("GrayWhaleMethod", "graywhalemethod.csv"))

# data = read.csv(here::here("60minutes.csv"))

# data = read.csv(here::here("FullMelAW.csv"))

#annotatedMelAW = read.csv(here::here("annotatedmelAWlowerhzoverlap.csv"))
# first 30 minutes is in this data set

#annotatedMelAW %>% arrange(desc(Time_End))
```




## Creating Training Data

```{r}

trainingdata = add_observations_linear(whaledf = data_train,
                                start_time = 0,
                                end_time =  7199.9,
                                num_time_steps = 1, 
                                numcep = 13,
                                step_size = 0.1)




table(trainingdata$Humpback)

```



## Creating Testing Data


```{r}
testingdata = add_observations_linear(whaledf = data_test,
                                start_time = 7200,
                                end_time =  max(data_test$Time_End),
                                num_time_steps = 1, 
                                numcep = 13,
                                step_size = 0.1)

testingdata

table(testingdata$Humpback)
```


## Loading in Annotations

```{r}
manual_annotations_evaluation = 
  read_excel(here::here("OrigData", "AW", "AWhb.xlsx")) %>% 
    rename(Begin_Time = 'Begin Time (s)', End_Time = 'End Time (s)') %>%
  filter(Begin_Time > min(testingdata$Time_Start) & End_Time < max(testingdata$Time_End))
```


## Creating Final Model

```{r}

#creating model
rfmod_1 <- rand_forest(min_n = 100, trees = 1000,
                       mtry = floor(sqrt(ncol(trainingdata) - 3))) %>%
  set_engine("ranger") %>%               
  set_mode("classification")            

#creating recipe
rfrecipe_1 <- recipe(Humpback ~ ., data = trainingdata) %>%
  step_rm(Time_Start, Time_End, X) %>%
  step_normalize(all_numeric_predictors()) %>%
  step_dummy(all_factor_predictors())


#creating workflow
rfworkflow_1 <- workflow() %>%
  add_model(rfmod_1) %>%
  add_recipe(rfrecipe_1)



#fitting model
rffit_1 <- rfworkflow_1 %>% fit(data = trainingdata)


```







## Predicting on Testing Data

```{r}
predictionsdf = testingdata %>% mutate(preds = predict(rffit_1, testingdata)$.pred_class)
# each run takes ~ 4 minutes
table(predictionsdf$preds)
```





## Creating Aggregation Grid

```{r}
agg_window_length = c(2, 4, 6, 8)
#agg_window_threshold = seq(0.5, 1, by = 0.05)

# 
# agg_window_length = c(2)
agg_window_threshold = c(0.5)

```


```{r}



grid <- expand.grid(
  lengths = agg_window_length,
  thresholds = agg_window_threshold
)

grid

```



## Metrics Type 1

```{r}
whale_call_metrics_type1 <- function(row, predictionsdf) {
  agg_window_length <- as.numeric(row[1])
  agg_window_threshold <- as.numeric(row[2])

  rolling_average <- rolling_avg_df(
    predictionsdf,
    agg_window_length,
    agg_window_threshold
  )
  
  print(rolling_average)
    
  if (nrow(rolling_average %>% filter(rolling_avg_prediction == 1)) == 0) {
    rfeval_recall <- 0
    rfeval_precision <- NA
    
  } else if (nrow(rolling_average %>% filter(rolling_avg_prediction == 0)) == 0) {
    rfeval_recall <- 1
    rfeval_precision <- nrow(rolling_average %>% filter(Humpback == 1)) /
      nrow(rolling_average %>% filter(rolling_avg_prediction == 1))
    
  } else if (nrow(rolling_average %>% filter(Humpback == 1)) == 0) {
    rfeval_recall <- NA
    rfeval_precision <- 0
    
  } else {
    rfeval_recall <- rolling_average %>%
      recall(truth = Humpback, estimate = rolling_avg_prediction, event_level = "second") %>%
      pull(.estimate)
    
    rfeval_precision <- rolling_average %>%
      precision(truth = Humpback, estimate = rolling_avg_prediction, event_level = "second") %>%
      pull(.estimate)
  }
  
  rfeval_f1 <- (2 * rfeval_recall * rfeval_precision) / (rfeval_recall + rfeval_precision)
  rfeval_f2 <- (5 * rfeval_recall * rfeval_precision) / (rfeval_recall + 4 * rfeval_precision)
  
  data.frame(
    agg_window_length = agg_window_length,
    agg_window_threshold = agg_window_threshold,
    Recall = rfeval_recall,
    Precision = rfeval_precision,
    F1 = rfeval_f1,
    F2 = rfeval_f2
  )
}


final_df <- do.call(
  rbind,
  lapply(seq_len(nrow(grid)), function(i) {
    whale_call_metrics_type1(grid[i, ], predictionsdf)
  })
)

final_df
```



## Metrics Type 2


```{r}
whale_call_metrics_type2 <- function(row, predictionsdf) {
  agg_window_length <- as.numeric(row[1])
  agg_window_threshold <- as.numeric(row[2])

  rolling_average <- rolling_avg_df(
    predictionsdf,
    agg_window_length,
    agg_window_threshold
  )

  prediction_windows <- creating_prediction_windows(
    rolling_average,
    time_start = Time_Start,
    time_end = Time_End,
    value_col = rolling_avg_prediction
  )

  conf_matrix_table <- confusion_from_intervals(
    data_true = manual_annotations_evaluation,
    data_pred = prediction_windows,
    true_interval_start = Begin_Time,
    true_interval_end = End_Time,
    pred_interval_start = start_time,
    pred_interval_end = end_time
  )

  TP <- conf_matrix_table %>% dplyr::pull(TP)
  FN <- conf_matrix_table %>% dplyr::pull(FN)
  FP <- conf_matrix_table %>% dplyr::pull(FP)

  num_pred_windows <- nrow(prediction_windows)

  if (TP + FN == 0) {
    recall <- NA_real_
  } else {
    recall <- TP / (TP + FN)
  }

  if (TP + FP == 0) {
    precision <- NA_real_
  } else {
    precision <- TP / (TP + FP)
  }

  if (is.na(recall) || is.na(precision) || (recall + precision == 0)) {
    F1 <- NA_real_
  } else {
    F1 <- 2 * recall * precision / (recall + precision)
  }

  if (is.na(recall) || is.na(precision) || (4 * precision + recall == 0)) {
    F2 <- NA_real_
  } else {
    F2 <- 5 * precision * recall / (4 * precision + recall)
  }

  data.frame(
    agg_window_length = agg_window_length,
    agg_window_threshold = agg_window_threshold,
    num_pred_windows = num_pred_windows,
    recall = recall,
    precision = precision,
    F1 = F1,
    F2 = F2
  )
}

final_df_type2 <- do.call(
  rbind,
  lapply(seq_len(nrow(grid)), function(i) {
    whale_call_metrics_type2(grid[i, ], predictionsdf)
  })
)


sorted_df_type2 = final_df_type2 %>% data.frame() %>% arrange(desc(F2))

sorted_df_type2

manual_annotations_evaluation
```



## PR Curve



```{r}



sorted_df %>%
  ggplot(aes(x = recall, y = precision, color = as.factor(agg_window_length), group = as.factor(agg_window_length))) +
  geom_line() +
  geom_point() +
  scale_color_manual(values = c("red", "blue", "green", "yellow", "orange", "purple")) +
  scale_x_continuous(limits = c(0, 1)) +
  scale_y_continuous(limits = c(0.5, 1)) +
  labs(
    title = "Precision-Recall Curve of Different Number of Neighbors",
    x = "Recall",
    y = "Precision",
    color = "Window Length"
  ) +
  theme_minimal()
```





## Create Output For Raven Visualization

```{r}

raven_output = function(testingoutput, start, end){

  rftestingoutput = rfwindowpredictions %>% 
    dplyr::select(Time_Start, Time_End, Humpback, prediction)
  
  
  #creating dummy low and high frequencies
  
  rftestingoutput = rftestingoutput %>% mutate(low = rep(0, times = nrow(rftestingoutput)),
                           high = rep(2000, times = nrow(rftestingoutput)))
  
  
  rftestingoutput = rftestingoutput %>% filter(prediction == 1) %>% 
    rename("Begin Time (s)" = Time_Start, "End Time (s)" = Time_End, 
           "Low Freq (Hz)" = low, "High Freq (Hz)" = high) %>% 
    dplyr::select(c("Begin Time (s)", "End Time (s)", 
                    "Low Freq (Hz)", "High Freq (Hz)"))
  
  
  #create output 
  write.table(rftestingoutput, 
              paste0("graywhalemethodrfevalwindowpreds", start, end, ".txt"), 
              sep = "\t", row.names = FALSE, quote = FALSE)
}

raven_output(testingoutput = rftestingoutput,
             start = min(rfwindowpredictions$Time_Start),
             end = max(rfwindowpredictions$Time_End))

```